In [1]:
import os

os.getcwd()

'C:\\Users\\ASUS\\E-Commerce-Marketplace-Analytics'

In [2]:
os.listdir()

['.ipynb_checkpoints',
 'Data',
 'Ecommerce_Marketplace_Analytics.ipynb',
 'Notebooks']

In [3]:
os.listdir("Data")

['.ipynb_checkpoints', 'Raw']

In [4]:
os.listdir("Data/Raw")

['olist_customers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'product_category_name_translation.csv']

In [5]:
import pandas as pd

customers = pd.read_csv("Data/Raw/olist_customers_dataset.csv")
geolocation = pd.read_csv("Data/Raw/olist_geolocation_dataset.csv")
order_items = pd.read_csv("Data/Raw/olist_order_items_dataset.csv")
order_payments = pd.read_csv("Data/Raw/olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("Data/Raw/olist_order_reviews_dataset.csv")
orders = pd.read_csv("Data/Raw/olist_orders_dataset.csv")
products = pd.read_csv("Data/Raw/olist_products_dataset.csv")
sellers = pd.read_csv("Data/Raw/olist_sellers_dataset.csv")
category_translation = pd.read_csv("Data/Raw/product_category_name_translation.csv")

In [6]:
print("Customers:", customers.shape)
print("Geolocation:", geolocation.shape)
print("Order Items:", order_items.shape)
print("Order Payments:", order_payments.shape)
print("Order Reviews:", order_reviews.shape)
print("Orders:", orders.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Category Translation:", category_translation.shape)

Customers: (99441, 5)
Geolocation: (1000163, 5)
Order Items: (112650, 7)
Order Payments: (103886, 5)
Order Reviews: (99224, 7)
Orders: (99441, 8)
Products: (32951, 9)
Sellers: (3095, 4)
Category Translation: (71, 2)

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [9]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [10]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [11]:
orders["order_status"].value_counts(normalize=True) * 100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [12]:
orders.groupby("order_status")[
    ["order_approved_at",
     "order_delivered_carrier_date",
     "order_delivered_customer_date"]
].apply(lambda x: x.isnull().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

In [13]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [14]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [15]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [16]:
customers["customer_unique_id"].nunique()

96096

In [17]:
customers["customer_id"].nunique()

99441

In [18]:
customers.duplicated().sum()

np.int64(0)

In [19]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [20]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [21]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [22]:
order_items["order_id"].nunique()

98666

In [23]:
order_items["product_id"].nunique()

32951

In [24]:
order_items["seller_id"].nunique()

3095

In [25]:
order_items["order_item_id"].value_counts().sort_index()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [26]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [27]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [28]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [29]:
products["product_category_name"].nunique()

73

In [30]:
products["product_category_name"].value_counts().head(15)

product_category_name
cama_mesa_banho                3029
esporte_lazer                  2867
moveis_decoracao               2657
beleza_saude                   2444
utilidades_domesticas          2335
automotivo                     1900
informatica_acessorios         1639
brinquedos                     1411
relogios_presentes             1329
telefonia                      1134
bebes                           919
perfumaria                      868
papelaria                       849
fashion_bolsas_e_acessorios     849
cool_stuff                      789
Name: count, dtype: int64

In [31]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

# Payments

In [32]:
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [33]:
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [34]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

## payment behavior

In [35]:
order_payments["order_id"].nunique()

99440

In [36]:
order_payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [37]:
order_payments["payment_installments"].value_counts().sort_index().head(15)

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
Name: count, dtype: int64

In [38]:
order_payments["order_id"].nunique()

99440

# Reviews

In [39]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [40]:
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [41]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

## Review score distribution

In [42]:
order_reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [43]:
order_reviews["review_score"].mean()

np.float64(4.08642062404257)

In [44]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [45]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [46]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Geolocation

In [47]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [48]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [49]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

# Data Cleaning

Make copies of the raw datasets

In [50]:
customers_clean = customers.copy()
orders_clean = orders.copy()
order_items_clean = order_items.copy()
order_payments_clean = order_payments.copy()
order_reviews_clean = order_reviews.copy()
products_clean = products.copy()
sellers_clean = sellers.copy()
geolocation_clean = geolocation.copy()
category_translation_clean = category_translation.copy()

print("Clean copies created successfully!")

Clean copies created successfully!

In [51]:
order_date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in order_date_cols:
    orders_clean[col] = pd.to_datetime(orders_clean[col])

In [52]:
orders_clean[order_date_cols].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [53]:
order_items_clean["shipping_limit_date"] = pd.to_datetime(
    order_items_clean["shipping_limit_date"]
)

order_items_clean["shipping_limit_date"].dtype

dtype('<M8[ns]')

In [54]:
order_reviews_clean["review_creation_date"] = pd.to_datetime(
    order_reviews_clean["review_creation_date"]
)

order_reviews_clean["review_answer_timestamp"] = pd.to_datetime(
    order_reviews_clean["review_answer_timestamp"]
)

order_reviews_clean[
    ["review_creation_date", "review_answer_timestamp"]
].dtypes

review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [55]:
print("Customers:", customers_clean.duplicated().sum())
print("Orders:", orders_clean.duplicated().sum())
print("Order Items:", order_items_clean.duplicated().sum())
print("Payments:", order_payments_clean.duplicated().sum())
print("Reviews:", order_reviews_clean.duplicated().sum())
print("Products:", products_clean.duplicated().sum())
print("Sellers:", sellers_clean.duplicated().sum())
print("Geolocation:", geolocation_clean.duplicated().sum())
print("Category Translation:", category_translation_clean.duplicated().sum())

Customers: 0
Orders: 0
Order Items: 0
Payments: 0
Reviews: 0
Products: 0
Sellers: 0
Geolocation: 261831
Category Translation: 0

In [56]:
print("Total geolocation rows:", len(geolocation_clean))

print(
    "Unique ZIP prefixes:",
    geolocation_clean["geolocation_zip_code_prefix"].nunique()
)

Total geolocation rows: 1000163
Unique ZIP prefixes: 19015

In [57]:
geolocation_clean[
    ["geolocation_zip_code_prefix", "geolocation_city", "geolocation_state"]
].drop_duplicates().shape

(27912, 3)

In [58]:
print("Customers - customer_id:",
      customers_clean["customer_id"].nunique(),
      "/",
      len(customers_clean))

print("Customers - customer_unique_id:",
      customers_clean["customer_unique_id"].nunique(),
      "/",
      len(customers_clean))

print("Orders - order_id:",
      orders_clean["order_id"].nunique(),
      "/",
      len(orders_clean))

print("Products - product_id:",
      products_clean["product_id"].nunique(),
      "/",
      len(products_clean))

print("Sellers - seller_id:",
      sellers_clean["seller_id"].nunique(),
      "/",
      len(sellers_clean))

Customers - customer_id: 99441 / 99441
Customers - customer_unique_id: 96096 / 99441
Orders - order_id: 99441 / 99441
Products - product_id: 32951 / 32951
Sellers - seller_id: 3095 / 3095

In [59]:
missing_customers = (
    ~orders_clean["customer_id"].isin(customers_clean["customer_id"])
).sum()

print("Orders with missing customer:", missing_customers)

Orders with missing customer: 0

In [60]:
missing_orders = (
    ~order_items_clean["order_id"].isin(orders_clean["order_id"])
).sum()

print("Order items with missing order:", missing_orders)

Order items with missing order: 0

In [61]:
missing_products = (
    ~order_items_clean["product_id"].isin(products_clean["product_id"])
).sum()

print("Order items with missing product:", missing_products)

Order items with missing product: 0

In [62]:
missing_sellers = (
    ~order_items_clean["seller_id"].isin(sellers_clean["seller_id"])
).sum()

print("Order items with missing seller:", missing_sellers)

Order items with missing seller: 0

Missing-Value Analysis

In [63]:
orders_clean.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [64]:
orders_clean[orders_clean.isnull().any(axis=1)]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered        23
created           5
approved          2
Name: count, dtype: int64

#### Investigate delivered orders with missing values

In [65]:
delivered_missing = orders_clean[
    (orders_clean["order_status"] == "delivered") &
    (
        orders_clean[
            [
                "order_approved_at",
                "order_delivered_carrier_date",
                "order_delivered_customer_date"
            ]
        ].isnull().any(axis=1)
    )
]

delivered_missing

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
5323,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17
16567,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
22663,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31
23156,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01
38290,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27
39334,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
48401,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20
63052,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29
67697,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21
72407,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23
73222,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaT,2017-11-20 19:44:47,2017-11-14
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
84999,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [66]:
delivered_missing[
    [
        "order_id",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].isnull().sum()

order_id                          0
order_approved_at                14
order_delivered_carrier_date      2
order_delivered_customer_date     8
dtype: int64

## 6.1 Investigating Missing Values in Delivered Orders

Missing values in the Orders table were analyzed based on business context rather than being removed or filled blindly.

Most missing delivery timestamps are expected because some orders were still processing, shipped, canceled, or unavailable.

However, orders marked as **delivered** should normally contain delivery timestamps. Therefore, delivered orders with missing date values are treated as potential data-quality anomalies and investigated separately.

These records will not be deleted automatically. They will only be excluded from calculations that specifically require the missing timestamp.

In [67]:
print("orders_clean" in globals())

True

In [68]:
delivered_missing = orders_clean[
    (orders_clean["order_status"] == "delivered") &
    (
        orders_clean[
            [
                "order_approved_at",
                "order_delivered_carrier_date",
                "order_delivered_customer_date"
            ]
        ].isnull().any(axis=1)
    )
]

delivered_missing

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
5323,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17
16567,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
22663,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31
23156,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01
38290,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27
39334,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
48401,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20
63052,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29
67697,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21
72407,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23
73222,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaT,2017-11-20 19:44:47,2017-11-14
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
84999,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [69]:
delivered_missing[
    [
        "order_id",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].isnull().sum()

order_id                          0
order_approved_at                14
order_delivered_carrier_date      2
order_delivered_customer_date     8
dtype: int64

In [70]:
id_cols = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]

delivered_missing.groupby(
    delivered_missing[id_cols].isnull().apply(
        lambda row: " | ".join(row.index[row].tolist()),
        axis=1
    )
).size()

order_approved_at                                               14
order_delivered_carrier_date                                     1
order_delivered_carrier_date | order_delivered_customer_date     1
order_delivered_customer_date                                    7
dtype: int64

## 6.2 Data-Quality Decision for Delivered Orders

A small number of orders marked as `delivered` have missing delivery-related timestamps.

There are 23 affected delivered orders:
- 14 missing approval timestamps
- 2 missing carrier-delivery timestamps
- 8 missing customer-delivery timestamps

The records are retained because they contain valid order information and may still be useful for revenue, order-volume, and customer analyses.

For calculations that require a specific timestamp, such as delivery duration, only records with the required dates will be included. This avoids introducing artificial values or unnecessarily removing valid business records.

### Finding: Delivered Orders with Missing Timestamps

Among delivered orders, 23 unique orders contain at least one missing timestamp:

- 14 orders are missing `order_approved_at`
- 1 order is missing only `order_delivered_carrier_date`
- 1 order is missing both carrier and customer delivery dates
- 7 orders are missing only `order_delivered_customer_date`

These records are retained in the cleaned dataset. They will only be excluded from calculations where the required timestamp is unavailable.

In [71]:
delivery_analysis = orders_clean[
    (orders_clean["order_status"] == "delivered") &
    (orders_clean["order_delivered_customer_date"].notna()) &
    (orders_clean["order_delivered_carrier_date"].notna())
].copy()

print("Total delivered orders:", (orders_clean["order_status"] == "delivered").sum())
print("Orders available for delivery analysis:", len(delivery_analysis))

Total delivered orders: 96478
Orders available for delivery analysis: 96469

## 6.3 Delivery Analysis Dataset

A separate dataset, `delivery_analysis`, was created for delivery-performance calculations.

Of 96,478 delivered orders, 96,469 contain both:
- `order_delivered_carrier_date`
- `order_delivered_customer_date`

These 96,469 orders can therefore be used to calculate delivery duration reliably.

The 9 delivered orders missing one of these required timestamps are retained in the main dataset but excluded from delivery-duration calculations only.

In [72]:
delivery_analysis["delivery_days"] = (
    delivery_analysis["order_delivered_customer_date"]
    - delivery_analysis["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

In [73]:
delivery_analysis["delivery_days"].describe()

count    96469.000000
mean        12.557804
std          9.545342
min          0.533414
25%          6.766146
50%         10.217454
75%         15.720069
max        209.628611
Name: delivery_days, dtype: float64

## 6.3 Delivery Time Analysis

Delivery duration is calculated as the number of days between the order purchase timestamp and the actual customer delivery timestamp.

For the 96,469 delivered orders with both required delivery timestamps:

- Average delivery time: 12.56 days
- Median delivery time: 10.22 days
- Minimum delivery time: 0.53 days
- 75% of orders were delivered within 15.72 days
- Maximum delivery time: 209.63 days

The large maximum value indicates the presence of extreme delivery-duration observations. These records will be investigated separately before deciding whether they should be excluded from specific analyses.

In [74]:
delivery_analysis[
    delivery_analysis["delivery_days"] > 60
][
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_days"
    ]
].sort_values("delivery_days", ascending=False).head(20)

,order_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,delivery_days
19590,ca07593549f1816d26a572e06dc1eab6,delivered,2017-02-21 23:31:27,2017-09-19 14:36:39,2017-03-22,209.628611
55619,1b3190b2dfa9d789e1f14c05b647a14a,delivered,2018-02-23 14:57:35,2018-09-19 23:24:07,2018-03-15,208.351759
61610,440d0d17af552815d15a9e41abe49359,delivered,2017-03-07 23:59:51,2017-09-19 15:12:50,2017-04-07,195.634016
70307,2fb597c2f772eca01b1f5c561bf6cc7b,delivered,2017-03-08 18:09:02,2017-09-19 14:33:17,2017-04-17,194.850174
89130,285ab9426d6982034523a855f55a885e,delivered,2017-03-08 22:47:40,2017-09-19 14:00:04,2017-04-06,194.633611
38509,0f4519c5f1c541ddec9f21b3bddd533a,delivered,2017-03-09 13:26:57,2017-09-19 14:38:21,2017-04-11,194.049583
11399,47b40429ed8cce3aee9199792275433f,delivered,2018-01-03 09:44:01,2018-07-13 20:51:31,2018-01-19,191.463542
81401,2fe324febf907e3ea3f2aa9650869fa5,delivered,2017-03-13 20:17:10,2017-09-19 17:00:07,2017-04-05,189.863160
54480,2d7561026d542c8dbd8f0daeadf67a43,delivered,2017-03-15 11:24:27,2017-09-19 14:38:18,2017-04-13,188.134618
68769,c27815f7e3dd0b926b58552628481575,delivered,2017-03-15 23:23:17,2017-09-19 17:14:25,2017-04-10,187.743843
62286,437222e3fd1b07396f1d9ba8c15fba59,delivered,2017-03-16 11:36:00,2017-09-19 16:28:58,2017-04-28,187.203449
31228,dfe5f68118c2576143240b8d78e5940a,delivered,2017-03-17 12:32:22,2017-09-19 18:13:19,2017-04-19,186.236771
74117,6e82dcfb5eada6283dba34f164e636f5,delivered,2017-05-17 19:09:02,2017-11-16 10:56:45,2017-06-14,182.658137
66407,2ba1366baecad3c3536f27546d129017,delivered,2017-02-28 14:56:37,2017-08-28 16:23:46,2017-03-29,181.060521
40847,d24e8541128cea179a11a65176e0a96f,delivered,2017-06-12 13:14:11,2017-12-04 18:36:29,2017-06-26,175.223819
64489,3566eabb132f8d64741ae7b921bbd10e,delivered,2017-03-29 13:57:55,2017-09-19 15:07:09,2017-05-05,174.048079
86520,ed8e9faf1b75f43ee027103957135663,delivered,2017-11-29 15:10:14,2018-05-21 18:22:18,2017-12-19,173.133380
74759,2fa29503f2ebd9f53deba187160f3202,delivered,2017-03-31 15:03:51,2017-09-19 18:24:46,2017-05-10,172.139525
37973,df6d8b7768a047c2981bae0a24afbb01,delivered,2017-04-04 10:46:22,2017-09-19 15:08:19,2017-05-10,168.181910
29519,4fbc8d6f2f4db3e789d5a876fa349b56,delivered,2018-02-02 21:38:36,2018-07-20 23:37:50,2018-03-08,168.082801

In [75]:
delivery_analysis["delivery_delay_days"] = (
    delivery_analysis["order_delivered_customer_date"]
    - delivery_analysis["order_estimated_delivery_date"]
).dt.total_seconds() / (24 * 60 * 60)

delivery_analysis[
    delivery_analysis["delivery_days"] > 60
][
    [
        "order_id",
        "delivery_days",
        "order_estimated_delivery_date",
        "order_delivered_customer_date",
        "delivery_delay_days"
    ]
].sort_values("delivery_days", ascending=False).head(20)

,order_id,delivery_days,order_estimated_delivery_date,order_delivered_customer_date,delivery_delay_days
19590,ca07593549f1816d26a572e06dc1eab6,209.628611,2017-03-22,2017-09-19 14:36:39,181.608785
55619,1b3190b2dfa9d789e1f14c05b647a14a,208.351759,2018-03-15,2018-09-19 23:24:07,188.975081
61610,440d0d17af552815d15a9e41abe49359,195.634016,2017-04-07,2017-09-19 15:12:50,165.633912
70307,2fb597c2f772eca01b1f5c561bf6cc7b,194.850174,2017-04-17,2017-09-19 14:33:17,155.606447
89130,285ab9426d6982034523a855f55a885e,194.633611,2017-04-06,2017-09-19 14:00:04,166.583380
38509,0f4519c5f1c541ddec9f21b3bddd533a,194.049583,2017-04-11,2017-09-19 14:38:21,161.609965
11399,47b40429ed8cce3aee9199792275433f,191.463542,2018-01-19,2018-07-13 20:51:31,175.869109
81401,2fe324febf907e3ea3f2aa9650869fa5,189.863160,2017-04-05,2017-09-19 17:00:07,167.708414
54480,2d7561026d542c8dbd8f0daeadf67a43,188.134618,2017-04-13,2017-09-19 14:38:18,159.609931
68769,c27815f7e3dd0b926b58552628481575,187.743843,2017-04-10,2017-09-19 17:14:25,162.718345
62286,437222e3fd1b07396f1d9ba8c15fba59,187.203449,2017-04-28,2017-09-19 16:28:58,144.686782
31228,dfe5f68118c2576143240b8d78e5940a,186.236771,2017-04-19,2017-09-19 18:13:19,153.759248
74117,6e82dcfb5eada6283dba34f164e636f5,182.658137,2017-06-14,2017-11-16 10:56:45,155.456076
66407,2ba1366baecad3c3536f27546d129017,181.060521,2017-03-29,2017-08-28 16:23:46,152.683171
40847,d24e8541128cea179a11a65176e0a96f,175.223819,2017-06-26,2017-12-04 18:36:29,161.775336
64489,3566eabb132f8d64741ae7b921bbd10e,174.048079,2017-05-05,2017-09-19 15:07:09,137.629965
86520,ed8e9faf1b75f43ee027103957135663,173.133380,2017-12-19,2018-05-21 18:22:18,153.765486
74759,2fa29503f2ebd9f53deba187160f3202,172.139525,2017-05-10,2017-09-19 18:24:46,132.767199
37973,df6d8b7768a047c2981bae0a24afbb01,168.181910,2017-05-10,2017-09-19 15:08:19,132.630775
29519,4fbc8d6f2f4db3e789d5a876fa349b56,168.082801,2018-03-08,2018-07-20 23:37:50,134.984606

In [76]:
extreme_delays = delivery_analysis[
    delivery_analysis["delivery_days"] > 60
]

print("Orders taking more than 60 days:", len(extreme_delays))
print(
    "Percentage of delivery-analysis orders:",
    round(len(extreme_delays) / len(delivery_analysis) * 100, 2),
    "%"
)

Orders taking more than 60 days: 306
Percentage of delivery-analysis orders: 0.32 %

## 6.5 Delivery Performance Against Estimated Date

Delivery performance is evaluated by comparing the actual customer delivery date with the estimated delivery date.

The classification is:

- **Early:** Actual delivery occurred before the estimated date.
- **On Time:** Actual delivery occurred on the estimated date.
- **Late:** Actual delivery occurred after the estimated date.

This metric helps evaluate whether the marketplace met its promised delivery expectations.

Extreme delays are retained in the analysis because they represent genuine observations in the source dataset. Their impact will be considered separately from the normal delivery pattern.

In [77]:
print("Delivered before estimated date:",
      (delivery_analysis["delivery_delay_days"] < 0).sum())

print("Delivered on estimated date:",
      (delivery_analysis["delivery_delay_days"] == 0).sum())

print("Delivered after estimated date:",
      (delivery_analysis["delivery_delay_days"] > 0).sum())

Delivered before estimated date: 88644
Delivered on estimated date: 0
Delivered after estimated date: 7825

In [78]:
delivery_performance = {
    "Early": (delivery_analysis["delivery_delay_days"] < 0).sum(),
    "On Time": (delivery_analysis["delivery_delay_days"] == 0).sum(),
    "Late": (delivery_analysis["delivery_delay_days"] > 0).sum()
}

delivery_performance_pct = {
    k: round(v / len(delivery_analysis) * 100, 2)
    for k, v in delivery_performance.items()
}

delivery_performance_pct

{'Early': np.float64(91.89),
 'On Time': np.float64(0.0),
 'Late': np.float64(8.11)}

## 6.6 Delivery Status Classification Adjustment

The initial delivery-status calculation compared the complete delivery timestamp with the estimated delivery timestamp.

This resulted in zero orders being classified as exactly on time because the actual delivery records contain time-of-day information while the estimated delivery field is represented as a date.

To make the business KPI meaningful, delivery performance is therefore evaluated at the calendar-date level:

- **Early:** Actual delivery date is before the estimated date.
- **On Time:** Actual delivery date matches the estimated date.
- **Late:** Actual delivery date is after the estimated date.

This prevents time-of-day differences from incorrectly classifying an order delivered on the estimated calendar date as late.

In [79]:
delivery_analysis["actual_delivery_date"] = (
    delivery_analysis["order_delivered_customer_date"].dt.normalize()
)

delivery_analysis["estimated_delivery_date"] = (
    delivery_analysis["order_estimated_delivery_date"].dt.normalize()
)

delivery_analysis["delivery_delay_days"] = (
    delivery_analysis["actual_delivery_date"]
    - delivery_analysis["estimated_delivery_date"]
).dt.days

In [80]:
delivery_analysis["delivery_status"] = delivery_analysis["delivery_delay_days"].apply(
    lambda x: "Early" if x < 0
    else "On Time" if x == 0
    else "Late"
)

delivery_status_counts = delivery_analysis["delivery_status"].value_counts()

delivery_status_pct = (
    delivery_analysis["delivery_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(delivery_status_counts)
print()
print(delivery_status_pct)

delivery_status
Early      88644
Late        6533
On Time     1292
Name: count, dtype: int64

delivery_status
Early      91.89
Late        6.77
On Time     1.34
Name: proportion, dtype: float64

## 6.7 Severity of Late Deliveries

In addition to measuring the percentage of late orders, the severity of late deliveries is analyzed.

This analysis focuses only on orders classified as `Late` and measures the number of days between the estimated and actual delivery dates.

The median delay is particularly useful because extreme delays can significantly increase the average.

In [81]:
late_orders = delivery_analysis[
    delivery_analysis["delivery_status"] == "Late"
]

late_orders["delivery_delay_days"].describe()

count    6533.000000
mean       10.620848
std        14.645964
min         1.000000
25%         3.000000
50%         7.000000
75%        13.000000
max       188.000000
Name: delivery_delay_days, dtype: float64

## 6.8 Delivery Performance Summary

The delivery analysis evaluates both delivery speed and adherence to estimated delivery dates.

Key metrics include:

- Average and median delivery duration
- Early, on-time, and late delivery rates
- Average and median delay among late orders
- Frequency of extreme delivery durations

The analysis uses calendar dates when comparing actual and estimated delivery dates to avoid incorrectly classifying orders based solely on time-of-day differences.

Extreme delivery records are retained rather than removed and are reported separately as operational exceptions.

In [82]:
delivery_kpis = {
    "Total delivered orders analyzed": len(delivery_analysis),
    "Average delivery time (days)": round(
        delivery_analysis["delivery_days"].mean(), 2
    ),
    "Median delivery time (days)": round(
        delivery_analysis["delivery_days"].median(), 2
    ),
    "Early delivery rate (%)": round(
        (delivery_analysis["delivery_status"] == "Early").mean() * 100, 2
    ),
    "On-time delivery rate (%)": round(
        (delivery_analysis["delivery_status"] == "On Time").mean() * 100, 2
    ),
    "Late delivery rate (%)": round(
        (delivery_analysis["delivery_status"] == "Late").mean() * 100, 2
    ),
    "Average delay among late orders (days)": round(
        late_orders["delivery_delay_days"].mean(), 2
    ),
    "Median delay among late orders (days)": round(
        late_orders["delivery_delay_days"].median(), 2
    ),
    "Orders taking >60 days": len(extreme_delays),
    "Extreme delivery rate (%)": round(
        len(extreme_delays) / len(delivery_analysis) * 100, 2
    )
}

delivery_kpis

{'Total delivered orders analyzed': 96469,
 'Average delivery time (days)': np.float64(12.56),
 'Median delivery time (days)': 10.22,
 'Early delivery rate (%)': np.float64(91.89),
 'On-time delivery rate (%)': np.float64(1.34),
 'Late delivery rate (%)': np.float64(6.77),
 'Average delay among late orders (days)': np.float64(10.62),
 'Median delay among late orders (days)': 7.0,
 'Orders taking >60 days': 306,
 'Extreme delivery rate (%)': 0.32}

## 6.9 Delivery Performance Findings

The delivery analysis shows that 96,469 delivered orders had the required timestamps for delivery-performance analysis.

Key findings:

- Average delivery time was **12.56 days**.
- Median delivery time was **10.22 days**.
- **91.89%** of orders were delivered before the estimated delivery date.
- **1.34%** of orders were delivered on the estimated delivery date.
- **6.77%** of orders were delivered after the estimated delivery date.
- Among late orders, the median delay was **7 days**, while the average delay was **10.62 days**.
- **306 orders (0.32%)** took more than 60 days to reach the customer and were treated as extreme delivery-duration cases.

These results describe the historical Olist dataset and should not be interpreted as a current industry-wide delivery benchmark.

The delivery records were retained rather than removing extreme observations. This preserves the original business data while allowing exceptional delivery cases to be identified separately.

## 7. Product Data Quality

The product dataset contains missing values in product category information and physical product attributes.

Before applying any cleaning method, we will investigate whether these missing values occur in the same records and determine whether the affected products can be retained safely.

We will avoid deleting products or filling values without a clear analytical reason.

In [83]:
# Check missing values in the product dataset

products_clean.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

## 7.1 Investigating Missing Product Information

The product dataset contains:

- 610 products with missing category and related descriptive attributes.
- 2 products with missing physical dimensions such as weight, length, height, and width.

The missing values will be investigated at the row level to determine whether the 610 missing category records represent the same products and whether the 2 products with missing dimensions require special treatment.

In [84]:
# Investigate products with missing category information

missing_category = products_clean[
    products_clean["product_category_name"].isna()
]

missing_category.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

## 7.2 Checking Usage of Products with Missing Categories

Products with missing category information may still appear in the order-items dataset.

Before deciding how to treat these products, we will check whether they were actually purchased.

If these products are associated with orders, deleting them could remove valid sales information from revenue and product-level analysis.

In [85]:
# Check whether products with missing categories appear in orders

missing_category_products = set(
    products_clean.loc[
        products_clean["product_category_name"].isna(),
        "product_id"
    ]
)

sold_missing_category = order_items_clean[
    order_items_clean["product_id"].isin(missing_category_products)
]

print("Products with missing category:", len(missing_category_products))
print("Order-item records for these products:", len(sold_missing_category))
print("Unique products actually sold:", sold_missing_category["product_id"].nunique())
print("Unique orders containing these products:", sold_missing_category["order_id"].nunique())

Products with missing category: 610
Order-item records for these products: 1603
Unique products actually sold: 610
Unique orders containing these products: 1451

## 7.3 Decision: Retain Products with Missing Categories

All 610 products with missing category information appear in the order-items dataset.

These products account for:

- 1,603 order-item records
- 1,451 unique orders
- 610 unique products

Therefore, these products will **not be deleted**.

Deleting them could remove valid historical sales records and affect revenue, order-volume, and customer analyses.

For category-level analysis, the missing category values will later be represented as **"Unknown"** or **"Uncategorized"** rather than being removed.

The original `product_category_name` column will be preserved so that the raw information is not overwritten.

## 7.4 Investigating Missing Product Dimensions

Two products have missing values for physical dimensions:

- Weight
- Length
- Height
- Width

We will inspect these records before deciding whether to retain, exclude, or impute the missing values.

In [86]:
# Inspect products with missing physical dimensions

missing_dimensions = products_clean[
    products_clean[
        [
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ].isnull().any(axis=1)
]

missing_dimensions

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 7.5 Decision: Missing Product Dimensions

The investigation identified two products with missing physical dimensions.

- Product `8578` has category and descriptive information available, but its weight, length, height, and width are missing.
- Product `18851` has all product attributes missing except its product ID.

These products will be retained because missing product attributes do not necessarily mean that the product is invalid.

The missing physical measurements will not be artificially imputed because there is insufficient evidence to determine their true values.

Analyses involving product dimensions will use only records where the required measurements are available.

In [87]:
# Check whether the products with missing dimensions appear in order items

missing_dimension_product_ids = set(
    missing_dimensions["product_id"]
)

dimension_missing_sales = order_items_clean[
    order_items_clean["product_id"].isin(missing_dimension_product_ids)
]

print("Products with missing dimensions:", len(missing_dimension_product_ids))
print("Order-item records:", len(dimension_missing_sales))
print("Unique orders:", dimension_missing_sales["order_id"].nunique())
print("Total item price:", round(dimension_missing_sales["price"].sum(), 2))

Products with missing dimensions: 2
Order-item records: 18
Unique orders: 16
Total item price: 2497.0

## 7.6 Final Decision on Missing Product Attributes

The two products with missing physical dimensions appear in 18 order-item records across 16 unique orders, with a total item price of 2,497.00.

Therefore, both products are retained in the dataset.

Missing physical dimensions will not be artificially imputed because their actual values cannot be reliably determined from the available data.

For analyses involving product dimensions, only records with the required measurements will be included.

For general product, order, revenue, and customer analysis, these products remain part of the dataset.

In [88]:
# Create an analysis-friendly category column

products_clean["product_category_analysis"] = (
    products_clean["product_category_name"]
    .fillna("Unknown")
)

# Check the result
products_clean["product_category_analysis"].value_counts().head(10)

product_category_analysis
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

## 7.8 Translating Product Categories

The original product category names are stored in Portuguese.

The Olist dataset provides a separate category-translation table containing English equivalents.

We will merge the translation table with the cleaned product dataset while preserving the original Portuguese category column.

Products without a known category will remain classified as `Unknown`.

In [89]:
# Merge English category names into the product dataset

products_clean = products_clean.merge(
    category_translation_clean,
    on="product_category_name",
    how="left"
)

# Create the final English category column
products_clean["product_category_english"] = (
    products_clean["product_category_name_english"]
    .fillna("Unknown")
)

# Check the result
products_clean[
    [
        "product_category_name",
        "product_category_name_english",
        "product_category_english"
    ]
].head(10)

,product_category_name,product_category_name_english,product_category_english
0,perfumaria,perfumery,perfumery
1,artes,art,art
2,esporte_lazer,sports_leisure,sports_leisure
3,bebes,baby,baby
4,utilidades_domesticas,housewares,housewares
5,instrumentos_musicais,musical_instruments,musical_instruments
6,cool_stuff,cool_stuff,cool_stuff
7,moveis_decoracao,furniture_decor,furniture_decor
8,eletrodomesticos,home_appliances,home_appliances
9,brinquedos,toys,toys

## 7.9 Validating Product Category Translation

After merging the category translation table, we will verify that all non-missing Portuguese categories have a corresponding English category.

This validation helps ensure that the merge did not accidentally create unmatched categories or lose category information.

In [90]:
# Check for categories that did not receive an English translation

untranslated_categories = products_clean[
    products_clean["product_category_name"].notna() &
    products_clean["product_category_name_english"].isna()
]["product_category_name"].unique()

print("Number of untranslated categories:", len(untranslated_categories))
print("Untranslated categories:", untranslated_categories)

Number of untranslated categories: 2
Untranslated categories: ['pc_gamer' 'portateis_cozinha_e_preparadores_de_alimentos']

## 7.10 Investigating Untranslated Product Categories

The category translation table does not contain English translations for two product categories:

- `pc_gamer`
- `portateis_cozinha_e_preparadores_de_alimentos`

Before assigning labels manually, we will measure how many products and order-item records belong to these categories.

This prevents assumptions from being introduced into the cleaned dataset.

In [91]:
# Investigate the two untranslated categories

untranslated = [
    "pc_gamer",
    "portateis_cozinha_e_preparadores_de_alimentos"
]

untranslated_products = products_clean[
    products_clean["product_category_name"].isin(untranslated)
]

untranslated_product_ids = untranslated_products["product_id"]

untranslated_sales = order_items_clean[
    order_items_clean["product_id"].isin(untranslated_product_ids)
]

print("Products in untranslated categories:", len(untranslated_products))
print("Order-item records:", len(untranslated_sales))
print("Unique orders:", untranslated_sales["order_id"].nunique())
print("Total item price:", round(untranslated_sales["price"].sum(), 2))

print("\nProducts by category:")
print(
    untranslated_products["product_category_name"]
    .value_counts()
)

Products in untranslated categories: 13
Order-item records: 24
Unique orders: 22
Total item price: 5514.48

Products by category:
product_category_name
portateis_cozinha_e_preparadores_de_alimentos    10
pc_gamer                                          3
Name: count, dtype: int64

## 7.11 Handling Untranslated Product Categories

Two valid product categories were not included in the Olist English translation table.

They represent:

- `pc_gamer`: 3 products
- `portateis_cozinha_e_preparadores_de_alimentos`: 10 products

Together, these categories appear in 24 order-item records across 22 orders, with a total item price of 5,514.48.

Because the category meanings are clear, English labels will be assigned only in the analysis-friendly `product_category_english` column.

The original Portuguese category names and the official translation-table values will remain unchanged.

In [92]:
# Add English labels for the two categories missing from the translation table

category_fixes = {
    "pc_gamer": "gaming_pc",
    "portateis_cozinha_e_preparadores_de_alimentos": "kitchen_food_processors"
}

products_clean["product_category_english"] = (
    products_clean["product_category_english"]
    .replace(category_fixes)
)

# Validate that no known categories remain untranslated

untranslated_categories = products_clean[
    products_clean["product_category_name"].notna() &
    (products_clean["product_category_english"] == "Unknown")
]["product_category_name"].unique()

print("Remaining untranslated categories:", len(untranslated_categories))
print(untranslated_categories)

Remaining untranslated categories: 2
['pc_gamer' 'portateis_cozinha_e_preparadores_de_alimentos']

## 7.10 Resolving Remaining Untranslated Categories

Two valid product categories were not included in the official English translation table.

Because these categories are clearly interpretable, they will be manually translated only in the analysis column.

The original Portuguese category column and the official translation column will remain unchanged to preserve the source data.

In [93]:
category_fixes = {
    "pc_gamer": "gaming_pc",
    "portateis_cozinha_e_preparadores_de_alimentos": "kitchen_food_processors"
}

products_clean["product_category_english"] = (
    products_clean["product_category_name"]
    .map(category_fixes)
    .fillna(products_clean["product_category_english"])
)

products_clean[
    products_clean["product_category_name"].isin(category_fixes.keys())
][
    ["product_category_name", "product_category_english"]
]

                               product_category_name product_category_english
1628                                        pc_gamer                gaming_pc
5821   portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
7325   portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
7478                                        pc_gamer                gaming_pc
8819   portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
11039  portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
14266  portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
16182  portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
16930                                       pc_gamer                gaming_pc
17800  portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
18610  portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
26890  portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors
29919  portateis_cozinha_e_preparadores_de_alimentos  kitchen_food_processors

In [94]:
untranslated_categories = products_clean[
    products_clean["product_category_name"].notna() &
    (products_clean["product_category_english"] == "Unknown")
]["product_category_name"].unique()

print("Remaining untranslated categories:", len(untranslated_categories))
print(untranslated_categories)

Remaining untranslated categories: 0
[]

## 7.11 Product Data Quality Summary

The product data-quality investigation is now complete.

Key decisions:

- The 610 products with missing categories were retained because all of them have valid sales records.
- Missing categories are represented as `Unknown` for analysis.
- The 2 products with missing physical dimensions were retained without artificial imputation.
- The official category translation table was used wherever available.
- Two categories not included in the official translation table were manually translated in the analysis column:
  - `pc_gamer` → `gaming_pc`
  - `portateis_cozinha_e_preparadores_de_alimentos` → `kitchen_food_processors`
- The original category fields were preserved to maintain source-data integrity.
- Final validation confirmed that there are **0 remaining untranslated categories**.

The cleaned product dataset is therefore ready for further analysis.

## 8. Payment Data Quality

Payment data is important for revenue, payment-method, and customer spending analysis.

Before cleaning the payment dataset, we will investigate missing payment records and unusual payment-installment values.

Because a single order can contain multiple payment records, the payment table will not be treated as a one-row-per-order dataset.

In [95]:
orders_without_payment = orders_clean[
    ~orders_clean["order_id"].isin(order_payments_clean["order_id"])
]

print("Orders without payment records:", len(orders_without_payment))

orders_without_payment[
    [
        "order_id",
        "customer_id",
        "order_status",
        "order_purchase_timestamp"
    ]
]

Orders without payment records: 1

,order_id,customer_id,order_status,order_purchase_timestamp
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38

## 8.1 Investigating the Order Without a Payment Record

One delivered order does not have a corresponding record in the payment dataset.

Because the order has a valid order record and a `delivered` status, it should not be removed from the main order dataset.

We will check whether the order has associated order items, customer information, or review information before deciding how it should be handled in payment-related analysis.

In [96]:
missing_payment_order_id = orders_without_payment["order_id"].iloc[0]

print("Order ID:", missing_payment_order_id)

print("\nOrder items:")
print(
    order_items_clean[
        order_items_clean["order_id"] == missing_payment_order_id
    ]
)

print("\nCustomer:")
print(
    customers_clean[
        customers_clean["customer_id"] ==
        orders_without_payment["customer_id"].iloc[0]
    ]
)

print("\nReview:")
print(
    order_reviews_clean[
        order_reviews_clean["order_id"] == missing_payment_order_id
    ]
)

Order ID: bfbd0f9bdef84302105ad712db648a6c

Order items:
                               order_id  order_item_id  \
84389  bfbd0f9bdef84302105ad712db648a6c              1
84390  bfbd0f9bdef84302105ad712db648a6c              2
84391  bfbd0f9bdef84302105ad712db648a6c              3

                             product_id                         seller_id  \
84389  5a6b04657a4c5ee34285d1e4619a96b4  ecccfa2bb93b34a3bf033cc5d1dcdc69
84390  5a6b04657a4c5ee34285d1e4619a96b4  ecccfa2bb93b34a3bf033cc5d1dcdc69
84391  5a6b04657a4c5ee34285d1e4619a96b4  ecccfa2bb93b34a3bf033cc5d1dcdc69

      shipping_limit_date  price  freight_value
84389 2016-09-19 23:11:33  44.99           2.83
84390 2016-09-19 23:11:33  44.99           2.83
84391 2016-09-19 23:11:33  44.99           2.83

Customer:
                            customer_id                customer_unique_id  \
21125  86dc2ffce2dfff336de2f386a786e574  830d5b7aaa3b6f1e9ad63703bec97d23

       customer_zip_code_prefix         customer_city customer_state
21125                     14600  sao joaquim da barra             SP

Review:
                              review_id                          order_id  \
37547  6916ca4502d6d3bfd39818759d55d536  bfbd0f9bdef84302105ad712db648a6c

       review_score review_comment_title  \
37547             1                  NaN

                               review_comment_message review_creation_date  \
37547  nao recebi o produto e nem resposta da empresa           2016-10-06

      review_answer_timestamp
37547     2016-10-07 18:32:28

## 8.2 Decision: Order Without Payment Record

The investigation identified one order without a corresponding payment record.

The order contains valid customer and order-item information and has three associated order-item records with a combined item value of **134.97**.

The order also has a review with a score of **1**, where the customer reported that the product was not received.

Although the order is recorded as `delivered` in the order-status field, the available review information indicates a possible delivery or order-status inconsistency.

Because the payment record is genuinely absent, no payment value will be imputed.

The order will be retained in the main dataset, but it will be excluded from payment-based calculations where an actual payment record is required.

This preserves the original data while preventing an assumed payment value from affecting revenue or payment-method analysis.

## 8.3 Investigating Zero Payment Installments

The payment dataset contains two records where `payment_installments` is recorded as zero.

A zero installment value is not automatically treated as an error because payment behavior can differ by payment method.

We will inspect the payment type, payment value, and associated order status before deciding how these records should be handled.

In [97]:
zero_installments = order_payments_clean[
    order_payments_clean["payment_installments"] == 0
]

zero_installments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

## 8.4 Investigating Zero-Installment Payment Records

Two payment records contain `payment_installments = 0`.

Both records have a positive payment value and use `credit_card` as the payment method.

We will check the complete payment history of these orders and their order status before deciding whether the zero value should be treated as a data-quality issue.

In [98]:
zero_installment_order_ids = zero_installments["order_id"].unique()

print("Orders with zero-installment records:", len(zero_installment_order_ids))

print("\nComplete payment records for these orders:")
print(
    order_payments_clean[
        order_payments_clean["order_id"].isin(zero_installment_order_ids)
    ].sort_values(["order_id", "payment_sequential"])
)

print("\nOrder status:")
print(
    orders_clean[
        orders_clean["order_id"].isin(zero_installment_order_ids)
    ][
        ["order_id", "order_status", "order_purchase_timestamp"]
    ]
)

Orders with zero-installment records: 2

Complete payment records for these orders:
                               order_id  payment_sequential payment_type  \
79014  1a57108394169c0b47d8f876acc9ba2d                   2  credit_card
46982  744bade1fcf9ff3f31d860ace076d422                   2  credit_card

       payment_installments  payment_value
79014                     0         129.94
46982                     0          58.69

Order status:
                               order_id order_status order_purchase_timestamp
63782  744bade1fcf9ff3f31d860ace076d422    delivered      2018-04-22 11:34:42
66368  1a57108394169c0b47d8f876acc9ba2d    delivered      2018-05-15 16:25:14

## 8.5 Decision: Zero-Installment Payment Records

Two payment records contain `payment_installments = 0`.

Both records:

- Use `credit_card` as the payment method.
- Have positive payment values.
- Belong to orders with `delivered` status.
- Are valid payment records with no duplicate payment rows.

The zero installment values will be retained because there is insufficient evidence to determine whether they represent a data-entry issue or a specific payment-processing condition.

The values will not be replaced with `1`, since doing so would introduce an assumption that is not supported by the dataset.

For installment-based analysis, these records can be treated separately or excluded when calculating installment-specific metrics.

## 8.6 Payment Data Quality Summary

The payment data-quality investigation identified two issues:

1. **One delivered order has no payment record.**
   - The order contains valid order and customer information.
   - No payment value will be imputed.
   - The order will remain in the main dataset but will be excluded from payment-based calculations requiring a payment record.

2. **Two credit-card payment records have zero installments.**
   - Both have positive payment values and belong to delivered orders.
   - The zero values will be retained because their true meaning cannot be determined from the available data.
   - They will be handled separately when performing installment-specific analysis.

No payment records were deleted or artificially modified.

This approach preserves the original payment data while preventing unsupported assumptions from affecting financial analysis.

## 9. Review Data Quality

Customer reviews are important for analyzing customer satisfaction and identifying relationships between delivery performance and review scores.

The review dataset contains missing values in review titles and review messages. These fields are optional text fields, so missing values do not necessarily indicate invalid records.

We will first check the completeness of the key analytical fields before deciding how to handle the missing review text.

In [99]:
review_key_columns = [
    "review_id",
    "order_id",
    "review_score",
    "review_creation_date",
    "review_answer_timestamp"
]

print("Missing values in key review fields:")
print(order_reviews_clean[review_key_columns].isnull().sum())

print("\nDuplicate review records:")
print(order_reviews_clean.duplicated().sum())

print("\nUnique review IDs:")
print(order_reviews_clean["review_id"].nunique())

print("\nUnique orders with reviews:")
print(order_reviews_clean["order_id"].nunique())

Missing values in key review fields:
review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

Duplicate review records:
0

Unique review IDs:
98410

Unique orders with reviews:
98673

## 9.1 Investigating Multiple Reviews per Order

The review dataset contains fewer unique review IDs than unique reviewed orders, so the relationship between orders and reviews should be verified.

We will check whether any orders have multiple review records before deciding how reviews should be joined to order-level analysis.

In [100]:
reviews_per_order = (
    order_reviews_clean
    .groupby("order_id")
    .size()
    .sort_values(ascending=False)
)

print("Maximum reviews for a single order:", reviews_per_order.max())

print("\nOrders with multiple reviews:")
print(reviews_per_order[reviews_per_order > 1].head(20))

print("\nNumber of orders with multiple reviews:",
      (reviews_per_order > 1).sum())

Maximum reviews for a single order: 3

Orders with multiple reviews:
order_id
8e17072ec97ce29f0e1f111e598b0c85    3
c88b1d1b157a9999ce368f218a407141    3
03c939fd7fd3b38f8485a0f95798f1f6    3
df56136b8031ecd28e200bb18e6ddb2e    3
29062384ce4975f78aeba6a496510386    2
fd95ae805c63c534f1a64589e102225e    2
8b3c2785144e72ccba9b0213f0f1cd1e    2
82fd1196a459f594fb1d66e667fc74c4    2
ca263afd88a8a1200605adbd4b63cd7d    2
4703440eb9289d3769819920e98ec061    2
9b24c8496d87684865617cdb3eff7065    2
8b426ff8aa1c03dc173f1270133b408e    2
329aacec1c0231ed21bb1e2f8f4dc1e0    2
1a3ccc1695931b2cb7a95065e0c81e4b    2
5642f00882c2ab59e001778dc483135f    2
328d856c33d24e8aac1b90367ae7cd3a    2
8f5fac100b291e3c7c7c34ca50001b5a    2
169d7e0fd71d624d306f132acd791cbe    2
169ab175fb915582d84c0c5c95bb0fe3    2
bd859dd7a6a1b8c1df9fcb75c3604eaf    2
dtype: int64

Number of orders with multiple reviews: 547

## 9.2 Review Relationship and Data-Quality Decision

The review dataset contains complete values for all key analytical fields:

- Review ID
- Order ID
- Review score
- Review creation date
- Review answer timestamp

There are no exact duplicate rows.

The investigation found that **547 orders have multiple review records**, with a maximum of three reviews for a single order.

These records will be retained rather than deleted.

For order-level analysis, review data will be aggregated appropriately before joining it with other order-level datasets. This prevents multiple review records from artificially duplicating orders, revenue, or other business metrics.

The missing review titles and messages will also be retained as missing values because they are optional text fields and are not required for review-score analysis.

In [101]:
print("Review score distribution:")
print(order_reviews_clean["review_score"].value_counts().sort_index())

print("\nInvalid review scores:",
      (~order_reviews_clean["review_score"].between(1, 5)).sum())

Review score distribution:
review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

Invalid review scores: 0

## 9.3 Review Data Quality Summary

The review data-quality investigation is complete.

Key findings:

- All key review fields contain no missing values.
- There are no exact duplicate review records.
- Review scores range from **1 to 5**, with **0 invalid scores**.
- Some orders contain multiple review records, with **547 orders having more than one review**.
- Missing review titles and messages are retained because they are optional text fields.
- Review records will be aggregated appropriately before joining with order-level data to prevent duplication of business metrics.

The review dataset is suitable for customer-satisfaction and review-score analysis.

## 10. Geolocation Data Quality

The geolocation dataset contains geographic information associated with Brazilian ZIP-code prefixes.

The dataset contains a large number of records and many exact duplicates. Rather than deleting these records immediately, we will investigate the relationship between ZIP-code prefixes and geographic coordinates.

The geolocation table will be treated as a supporting lookup dataset rather than as a one-row-per-customer or one-row-per-order table.

In [102]:
print("Total geolocation rows:", len(geolocation_clean))

print("Unique ZIP-code prefixes:",
      geolocation_clean["geolocation_zip_code_prefix"].nunique())

print("Exact duplicate rows:",
      geolocation_clean.duplicated().sum())

print("\nMissing values:")
print(geolocation_clean.isnull().sum())

print("\nRows per ZIP-code prefix:")
print(
    geolocation_clean
    .groupby("geolocation_zip_code_prefix")
    .size()
    .describe()
)

Total geolocation rows: 1000163
Unique ZIP-code prefixes: 19015
Exact duplicate rows: 261831

Missing values:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Rows per ZIP-code prefix:
count    19015.000000
mean        52.598633
std         72.057907
min          1.000000
25%         10.000000
50%         29.000000
75%         66.500000
max       1146.000000
dtype: float64

## 10.1 Investigating Geographic Variation

The geolocation dataset contains multiple records for the same ZIP-code prefix.

This may represent multiple geographic coordinates within the same ZIP area rather than invalid duplicate business records.

Before reducing the dataset, we will check whether the coordinates and location names vary within ZIP-code prefixes.

This will determine whether an aggregated ZIP-level lookup should be created for later geographic analysis.

In [103]:
zip_variation = (
    geolocation_clean
    .groupby("geolocation_zip_code_prefix")
    .agg(
        coordinate_count=("geolocation_lat", "count"),
        unique_latitudes=("geolocation_lat", "nunique"),
        unique_longitudes=("geolocation_lng", "nunique"),
        unique_cities=("geolocation_city", "nunique"),
        unique_states=("geolocation_state", "nunique")
    )
)

print("ZIP prefixes with multiple coordinates:",
      (zip_variation["unique_latitudes"] > 1).sum())

print("ZIP prefixes with multiple cities:",
      (zip_variation["unique_cities"] > 1).sum())

print("ZIP prefixes with multiple states:",
      (zip_variation["unique_states"] > 1).sum())

print("\nSample ZIP prefixes with multiple coordinates:")
print(
    zip_variation[
        zip_variation["unique_latitudes"] > 1
    ].head(10)
)

ZIP prefixes with multiple coordinates: 17781
ZIP prefixes with multiple cities: 8556
ZIP prefixes with multiple states: 8

Sample ZIP prefixes with multiple coordinates:
                             coordinate_count  unique_latitudes  \
geolocation_zip_code_prefix
1001                                       26                10
1002                                       13                 6
1003                                       17                10
1004                                       22                14
1005                                       25                11
1006                                        9                 7
1007                                       26                15
1008                                       16                12
1009                                       41                 7
1010                                       18                 5

                             unique_longitudes  unique_cities  unique_states
geolocation_zip_code_prefix
1001                                        10              2              1
1002                                         6              2              1
1003                                        10              2              1
1004                                        14              2              1
1005                                        11              2              1
1006                                         7              2              1
1007                                        15              2              1
1008                                        12              2              1
1009                                         7              2              1
1010                                         5              2              1

## 10.2 Geolocation Data Quality Decision

The investigation shows that the geolocation dataset contains substantial geographic variation within ZIP-code prefixes:

- 17,781 ZIP prefixes have multiple latitude values.
- 8,556 ZIP prefixes have multiple city values.
- Only 8 ZIP prefixes contain multiple state values.

Therefore, the repeated records should not simply be deleted.

For geographic analysis, an aggregated ZIP-level lookup will be created using the mean latitude and longitude for each ZIP-code prefix.

The original geolocation dataset will be preserved, while the aggregated lookup will provide a simpler structure for joining geographic information to customer or seller data.

geolocation_zip = (
    geolocation_clean
    .groupby("geolocation_zip_code_prefix", as_index=False)
    .agg(
        latitude=("geolocation_lat", "mean"),
        longitude=("geolocation_lng", "mean"),
        city=("geolocation_city", "first"),
        state=("geolocation_state", "first")
    )
)

print("Original geolocation rows:", len(geolocation_clean))
print("ZIP-level lookup rows:", len(geolocation_zip))
print("Unique ZIP prefixes:", geolocation_zip["geolocation_zip_code_prefix"].nunique())

print("\nMissing values in ZIP-level lookup:")
print(geolocation_zip.isnull().sum())

print("\nSample:")
geolocation_zip.head()

## 10.3 Geolocation Data Quality Summary

The geolocation data-quality investigation is complete.

The raw dataset contains 1,000,163 records across 19,015 ZIP-code prefixes, with substantial geographic variation within many ZIP prefixes.

The original geolocation dataset has been preserved.

For analysis, an aggregated ZIP-level lookup named `geolocation_zip` was created with:

- Mean latitude
- Mean longitude
- Representative city
- State

The resulting lookup contains **19,015 unique ZIP-code prefixes** and has **no missing values**.

This ZIP-level lookup can be used for geographic analysis without unnecessarily removing information from the original dataset.

# 11. Final Data Validation

Before beginning exploratory and business analysis, the cleaned datasets will undergo a final validation check.

The purpose is to confirm that the key datasets are loaded correctly, required identifiers remain unique, and important analytical fields do not contain unexpected missing values.

This validation provides a final checkpoint before creating the analysis dataset.

In [104]:
print("FINAL DATA VALIDATION")
print("=" * 50)

print("\nCustomers")
print("Rows:", len(customers_clean))
print("Unique customer_id:", customers_clean["customer_id"].nunique())

print("\nOrders")
print("Rows:", len(orders_clean))
print("Unique order_id:", orders_clean["order_id"].nunique())

print("\nOrder Items")
print("Rows:", len(order_items_clean))
print("Unique order_id:", order_items_clean["order_id"].nunique())
print("Unique product_id:", order_items_clean["product_id"].nunique())

print("\nPayments")
print("Rows:", len(order_payments_clean))
print("Unique order_id:", order_payments_clean["order_id"].nunique())

print("\nReviews")
print("Rows:", len(order_reviews_clean))
print("Unique review_id:", order_reviews_clean["review_id"].nunique())
print("Unique order_id:", order_reviews_clean["order_id"].nunique())

print("\nProducts")
print("Rows:", len(products_clean))
print("Unique product_id:", products_clean["product_id"].nunique())

print("\nSellers")
print("Rows:", len(sellers_clean))
print("Unique seller_id:", sellers_clean["seller_id"].nunique())

print("\nGeolocation ZIP Lookup")
print("Rows:", len(geolocation_zip))
print("Unique ZIP prefixes:",
      geolocation_zip["geolocation_zip_code_prefix"].nunique())

FINAL DATA VALIDATION
==================================================

Customers
Rows: 99441
Unique customer_id: 99441

Orders
Rows: 99441
Unique order_id: 99441

Order Items
Rows: 112650
Unique order_id: 98666
Unique product_id: 32951

Payments
Rows: 103886
Unique order_id: 99440

Reviews
Rows: 99224
Unique review_id: 98410
Unique order_id: 98673

Products
Rows: 32951
Unique product_id: 32951

Sellers
Rows: 3095
Unique seller_id: 3095

Geolocation ZIP Lookup

NameError: name 'geolocation_zip' is not defined

## 12.1 Creating the Order-Item Analysis Dataset

The order-item level will be used as the foundation for product, category, seller, and revenue analysis.

Orders, customers, products, and sellers will be joined using their respective keys.

Payments and reviews will remain separate at this stage because an order can contain multiple payment or review records. Joining them directly could duplicate order-item records and produce incorrect revenue calculations.

The analysis dataset will preserve the original cleaned datasets while creating a separate DataFrame for business analysis.v

In [ ]:
order_item_analysis = (
    order_items_clean
    .merge(
        orders_clean,
        on="order_id",
        how="left"
    )
    .merge(
        customers_clean,
        on="customer_id",
        how="left"
    )
    .merge(
        products_clean[
            [
                "product_id",
                "product_category_name",
                "product_category_english"
            ]
        ],
        on="product_id",
        how="left"
    )
    .merge(
        sellers_clean,
        on="seller_id",
        how="left"
    )
)

print("Analysis dataset shape:", order_item_analysis.shape)

print("\nMissing values in key joined fields:")
print(
    order_item_analysis[
        [
            "order_id",
            "customer_id",
            "product_id",
            "seller_id",
            "product_category_english"
        ]
    ].isnull().sum()
)

print("\nSample:")
order_item_analysis.head()

## 12.2 Core Revenue KPIs

Revenue will be calculated from the `price` field in the order-item dataset.

The `price` field represents the item price, while `freight_value` represents the freight/shipping charge. They will be analyzed separately.

The following KPIs will be calculated:

- Total item revenue
- Total freight value
- Total order items
- Unique orders
- Average order value (AOV)

Average order value will be calculated at the order level so that orders containing multiple items are not counted multiple times.

In [ ]:
# Total item revenue
total_revenue = order_item_analysis["price"].sum()

# Total freight
total_freight = order_item_analysis["freight_value"].sum()

# Total order items
total_items = len(order_item_analysis)

# Unique orders
unique_orders = order_item_analysis["order_id"].nunique()

# Revenue per order
order_revenue = (
    order_item_analysis
    .groupby("order_id")["price"]
    .sum()
)

average_order_value = order_revenue.mean()

print("CORE REVENUE KPIs")
print("=" * 40)
print(f"Total item revenue: {total_revenue:,.2f}")
print(f"Total freight value: {total_freight:,.2f}")
print(f"Total order items: {total_items:,}")
print(f"Unique orders with items: {unique_orders:,}")
print(f"Average order value: {average_order_value:,.2f}")

## 12.3 Core Revenue Findings

The initial revenue analysis shows:

- Total item revenue of **13,591,643.70** across the available order-item records.
- Total freight value of **2,251,909.54**.
- **112,650** order-item records across **98,666** unique orders containing items.
- Average Order Value (AOV) of **137.75** based on item revenue aggregated at the order level.

Item revenue and freight value are kept as separate metrics because freight represents shipping charges rather than product sales revenue.

These KPIs provide the baseline for deeper analysis of revenue trends, product categories, customers, and sellers.

## 12.4 Monthly Revenue Analysis

Monthly revenue will be calculated using the order purchase date and item price.

This analysis will help identify revenue trends, periods of higher or lower sales activity, and potential seasonal patterns.

Revenue will be aggregated by month at the order-item level.

In [ ]:
monthly_revenue = (
    order_item_analysis
    .assign(
        order_month=order_item_analysis[
            "order_purchase_timestamp"
        ].dt.to_period("M")
    )
    .groupby("order_month")
    .agg(
        revenue=("price", "sum"),
        orders=("order_id", "nunique"),
        items=("order_id", "count")
    )
    .reset_index()
)

monthly_revenue["order_month"] = (
    monthly_revenue["order_month"].astype(str)
)

monthly_revenue["average_order_value"] = (
    monthly_revenue["revenue"] /
    monthly_revenue["orders"]
)

monthly_revenue.head()

In [ ]:
print("Number of months:", len(monthly_revenue))

print("\nHighest revenue months:")
print(
    monthly_revenue
    .sort_values("revenue", ascending=False)
    .head(10)
)

print("\nLowest revenue months:")
print(
    monthly_revenue
    .sort_values("revenue")
    .head(10)
)

## 12.5 Monthly Revenue Trend

The monthly revenue trend shows substantial growth in sales activity after the early months of the dataset.

The first and final months contain very few orders, indicating that the dataset has incomplete coverage at its boundaries. Therefore, these months should not be interpreted as normal low-demand periods.

Revenue reached its highest recorded monthly value in **November 2017**, with item revenue of **1,010,271.37** across **7,451 orders**.

Revenue remained relatively strong throughout much of 2018, with April and May 2018 each generating approximately **1 million** in item revenue.

The trend will be used to investigate revenue growth, sales volume, and potential seasonal patterns.

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.plot(
    monthly_revenue["order_month"],
    monthly_revenue["revenue"],
    marker="o"
)

plt.title("Monthly Item Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

In [ ]:
print("Revenue trend summary")
print("=" * 40)

print(
    "Highest revenue month:",
    monthly_revenue.loc[
        monthly_revenue["revenue"].idxmax(),
        "order_month"
    ]
)

print(
    "Highest monthly revenue:",
    f"{monthly_revenue['revenue'].max():,.2f}"
)

print(
    "Lowest revenue month:",
    monthly_revenue.loc[
        monthly_revenue["revenue"].idxmin(),
        "order_month"
    ]
)

print(
    "Lowest monthly revenue:",
    f"{monthly_revenue['revenue'].min():,.2f}"
)

## 12.6 Monthly Order Volume Analysis

Revenue can increase because of either:

- More orders being placed
- Higher spending per order
- A combination of both

Therefore, order volume will be analyzed alongside monthly revenue to understand what is driving the observed revenue trend.

The analysis will compare monthly revenue, unique orders, and Average Order Value (AOV).

In [ ]:
monthly_revenue["revenue_per_order"] = (
    monthly_revenue["revenue"] /
    monthly_revenue["orders"]
)

print("MONTHLY ORDER VOLUME")
print("=" * 40)

print(
    monthly_revenue[
        [
            "order_month",
            "revenue",
            "orders",
            "average_order_value"
        ]
    ].to_string(index=False)
)

In [ ]:
print("\nHighest order-volume months:")
print(
    monthly_revenue
    .sort_values("orders", ascending=False)
    .head(10)
    [
        [
            "order_month",
            "orders",
            "revenue",
            "average_order_value"
        ]
    ]
)

print("\nHighest AOV months:")
print(
    monthly_revenue
    .sort_values("average_order_value", ascending=False)
    .head(10)
    [
        [
            "order_month",
            "orders",
            "revenue",
            "average_order_value"
        ]
    ]
)

## 12.7 Revenue Driver Analysis

The comparison between monthly revenue, order volume, and Average Order Value (AOV) indicates that higher revenue periods are generally associated with higher order volumes.

For example, **November 2017** recorded the highest monthly revenue of **1,010,271.37** and also the highest order volume of **7,451 orders**, while its AOV was **135.59**, below several other months.

Similarly, several high-revenue months in 2018 had more than 6,000 orders without having the highest AOV.

This suggests that order volume was an important driver of revenue during the observed period.

AOV should be interpreted together with order volume because months with very few orders can produce unusually high or low AOV values that are less representative of normal business activity.

In [ ]:
revenue_order_correlation = monthly_revenue[
    ["revenue", "orders"]
].corr().iloc[0, 1]

revenue_aov_correlation = monthly_revenue[
    ["revenue", "average_order_value"]
].corr().iloc[0, 1]

print("Revenue vs Orders correlation:", round(revenue_order_correlation, 3))
print("Revenue vs AOV correlation:", round(revenue_aov_correlation, 3))

## 12.8 Revenue Driver Findings

The correlation analysis shows a very strong positive relationship between monthly revenue and order volume (**r = 0.996**).

In comparison, the relationship between monthly revenue and Average Order Value was considerably weaker (**r = 0.306**).

This indicates that, within the observed Olist dataset, higher monthly revenue was much more closely associated with a greater number of orders than with higher average spending per order.

Correlation measures association and does not establish causation. Therefore, this analysis identifies order volume as a strong revenue-related factor rather than proving that increasing order volume directly causes higher revenue.

## 13. Product Category Revenue Analysis

Product categories will be analyzed to identify the categories contributing the most item revenue.

Revenue will be calculated by summing the `price` of order items for each product category.

The analysis will examine:

- Total revenue by category
- Number of orders by category
- Number of items sold by category
- Average item price by category

The English category field created during data cleaning will be used for analysis.

In [ ]:
category_analysis = (
    order_item_analysis
    .groupby("product_category_english")
    .agg(
        revenue=("price", "sum"),
        orders=("order_id", "nunique"),
        items_sold=("product_id", "count"),
        average_item_price=("price", "mean")
    )
    .reset_index()
    .sort_values("revenue", ascending=False)
)

category_analysis.head(15)

In [ ]:
print("TOP 15 CATEGORIES BY REVENUE")
print("=" * 60)

print(
    category_analysis[
        [
            "product_category_english",
            "revenue",
            "orders",
            "items_sold",
            "average_item_price"
        ]
    ]
    .head(15)
    .to_string(index=False)
)

## 13.1 Product Category Revenue Findings

The category analysis shows that revenue is distributed across several major product categories.

**Health & Beauty** generated the highest item revenue at **1,258,681.34**, supported by **8,836 orders** and **9,670 items sold**.

**Watches & Gifts** generated **1,205,005.68** in item revenue despite having fewer orders than Health & Beauty. Its average item price of **201.14** was substantially higher, indicating that higher item value contributed to its revenue performance.

**Bed Bath Table** recorded the highest item volume among the top categories, with **11,115 items sold**, but its average item price was lower at **93.30**.

These differences demonstrate that category revenue can be influenced by both sales volume and average item price. Therefore, both metrics should be considered when evaluating category performance.

## 13.2 Revenue Concentration by Product Category

Revenue concentration will be analyzed to determine how much of total item revenue is generated by the highest-revenue product categories.

The analysis will calculate the revenue contribution of each category and identify the cumulative contribution of the top categories.

In [ ]:
category_analysis["revenue_share_pct"] = (
    category_analysis["revenue"] /
    category_analysis["revenue"].sum()
) * 100

category_analysis["cumulative_revenue_share_pct"] = (
    category_analysis["revenue_share_pct"].cumsum()
)

category_analysis.head(15)

In [ ]:
print("REVENUE CONCENTRATION")
print("=" * 50)

for n in [5, 10, 15]:
    share = category_analysis.head(n)["revenue_share_pct"].sum()
    print(f"Top {n} categories revenue share: {share:.2f}%")

## 13.3 Revenue Concentration Findings

The revenue concentration analysis shows that a relatively small number of product categories account for a substantial share of total item revenue.

- The top **5 categories** contribute **39.74%** of total category revenue.
- The top **10 categories** contribute **62.36%**.
- The top **15 categories** contribute **76.29%**.

This indicates that revenue is concentrated among a limited group of product categories rather than being evenly distributed across the marketplace.

The finding can help prioritize category-level analysis, seller performance investigation, inventory planning, and customer-demand analysis.

## 13.4 Category Volume vs Revenue Contribution

Revenue contribution does not always correspond directly to sales volume.

To understand this relationship, each category's share of total items sold will be compared with its share of total item revenue.

This comparison helps identify categories where revenue contribution is relatively high or low compared with their sales volume.

In [ ]:
category_analysis["item_volume_share_pct"] = (
    category_analysis["items_sold"] /
    category_analysis["items_sold"].sum()
) * 100

category_analysis["revenue_vs_volume_gap_pct"] = (
    category_analysis["revenue_share_pct"] -
    category_analysis["item_volume_share_pct"]
)

category_analysis[
    [
        "product_category_english",
        "revenue",
        "items_sold",
        "revenue_share_pct",
        "item_volume_share_pct",
        "revenue_vs_volume_gap_pct"
    ]
].head(15)

In [ ]:
print("Categories with the largest positive revenue-volume gap:")
print(
    category_analysis
    .sort_values("revenue_vs_volume_gap_pct", ascending=False)
    [
        [
            "product_category_english",
            "revenue_share_pct",
            "item_volume_share_pct",
            "revenue_vs_volume_gap_pct"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

print("\nCategories with the largest negative revenue-volume gap:")
print(
    category_analysis
    .sort_values("revenue_vs_volume_gap_pct")
    [
        [
            "product_category_english",
            "revenue_share_pct",
            "item_volume_share_pct",
            "revenue_vs_volume_gap_pct"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

## 13.5 Category Revenue vs Volume Findings

Comparing revenue share with item-volume share reveals meaningful differences across product categories.

**Watches & Gifts** has the largest positive revenue-volume gap among the analyzed categories:

- Revenue share: **8.87%**
- Item-volume share: **5.32%**
- Difference: **+3.55 percentage points**

This indicates that the category contributes a larger share of revenue relative to its share of items sold.

In contrast, several categories have negative revenue-volume gaps:

- **Bed & Bath Table:** **-2.24 percentage points**
- **Furniture & Decor:** **-2.03 percentage points**
- **Telephony:** **-1.65 percentage points**
- **Housewares:** **-1.53 percentage points**

These categories account for a larger share of item volume than of revenue.

The analysis describes revenue and sales-volume patterns only. It does not measure profitability because product costs and margins are not available in the dataset.

# 14. Customer Analysis

Customer-level analysis will be performed using `customer_unique_id`.

This identifier represents the unique customer across the marketplace, while `customer_id` can represent different records for the same customer.

The analysis will examine:

- Unique customers
- Orders per customer
- Repeat-purchase behavior
- Customer revenue contribution
- Customer segmentation based on purchase activity

In [ ]:
customer_orders = (
    order_item_analysis
    .groupby("customer_unique_id")
    .agg(
        orders=("order_id", "nunique"),
        items_purchased=("product_id", "count"),
        revenue=("price", "sum")
    )
    .reset_index()
)

print("CUSTOMER ANALYSIS")
print("=" * 40)

print("Unique customers:", customer_orders["customer_unique_id"].nunique())

print(
    "Customers with 1 order:",
    (customer_orders["orders"] == 1).sum()
)

print(
    "Customers with more than 1 order:",
    (customer_orders["orders"] > 1).sum()
)

print(
    "Maximum orders by one customer:",
    customer_orders["orders"].max()
)

## 14.1 Repeat Customer Analysis

Repeat purchasing will be measured using `customer_unique_id`.

A repeat customer is defined as a unique customer with more than one distinct order in the analysis dataset.

The repeat-customer rate will be calculated as the percentage of unique customers who placed more than one order.

In [ ]:
total_customers = customer_orders["customer_unique_id"].nunique()

repeat_customers = (
    customer_orders["orders"] > 1
).sum()

one_time_customers = (
    customer_orders["orders"] == 1
).sum()

repeat_customer_rate = (
    repeat_customers / total_customers
) * 100

print("CUSTOMER RETENTION OVERVIEW")
print("=" * 45)

print(f"Total unique customers: {total_customers:,}")
print(f"One-time customers: {one_time_customers:,}")
print(f"Repeat customers: {repeat_customers:,}")
print(f"Repeat customer rate: {repeat_customer_rate:.2f}%")

In [ ]:
print("ORDER FREQUENCY PER CUSTOMER")
print("=" * 45)

print(
    customer_orders["orders"]
    .value_counts()
    .sort_index()
    .head(10)
)

## 14.2 Customer Retention Findings

The customer analysis shows that **95,420 unique customers** placed orders in the analysis dataset.

Of these:

- **92,507 customers (96.95%)** placed only one order.
- **2,913 customers (3.05%)** placed more than one order.
- **2,673 repeat customers** placed exactly two orders.
- **192 customers** placed three orders.
- A small number of customers placed four or more orders, with the highest observed frequency being **16 orders**.

The observed repeat-customer rate is therefore **3.05%**.

This result describes repeat purchasing within the available Olist dataset and should not be interpreted as a general e-commerce retention benchmark.

In [ ]:
customer_orders["customer_type"] = customer_orders["orders"].apply(
    lambda x: "Repeat Customer" if x > 1 else "One-Time Customer"
)

customer_type_summary = (
    customer_orders
    .groupby("customer_type")
    .agg(
        customers=("customer_unique_id", "count"),
        revenue=("revenue", "sum"),
        orders=("orders", "sum")
    )
    .reset_index()
)

customer_type_summary["customer_share_pct"] = (
    customer_type_summary["customers"] /
    customer_type_summary["customers"].sum()
) * 100

customer_type_summary["revenue_share_pct"] = (
    customer_type_summary["revenue"] /
    customer_type_summary["revenue"].sum()
) * 100

customer_type_summary

## 14.3 Revenue Contribution by Customer Type

Customer count and revenue contribution are compared to understand whether repeat customers contribute disproportionately to marketplace revenue.

The analysis uses item revenue from the order-item dataset and separates customers into:

- One-Time Customers: customers with exactly one order
- Repeat Customers: customers with more than one order

In [ ]:
customer_type_summary = customer_type_summary[
    [
        "customer_type",
        "customers",
        "orders",
        "revenue",
        "customer_share_pct",
        "revenue_share_pct"
    ]
]

customer_type_summary

## 14.4 Customer Revenue Findings

The customer-type analysis shows a difference between customer share and revenue share.

- **One-time customers** represent **96.95%** of customers and contribute **94.38%** of item revenue.
- **Repeat customers** represent only **3.05%** of customers but contribute **5.62%** of item revenue.
- Repeat customers generated **6,159 orders** compared with **92,507 orders** from one-time customers.

The repeat-customer group therefore contributes a larger share of revenue than its share of the customer base.

This does not establish that repeat purchasing causes higher customer value, but it indicates that repeat customers are an important segment for further customer-value and retention analysis.

In [ ]:
customer_type_summary = customer_type_summary.copy()

customer_type_summary["revenue_per_customer"] = (
    customer_type_summary["revenue"] /
    customer_type_summary["customers"]
)

customer_type_summary[
    [
        "customer_type",
        "customers",
        "revenue",
        "revenue_per_customer"
    ]
]

## 14.6 Customer Value Findings

The average item revenue per customer differs substantially between one-time and repeat customers.

- One-time customers generated an average of **138.67** in item revenue per customer.
- Repeat customers generated an average of **262.03** in item revenue per customer.
- Repeat customers therefore generated approximately **1.89 times** the item revenue per customer compared with one-time customers.

This indicates that customers who purchased more than once contributed substantially more revenue per customer within the Olist dataset.

The analysis measures item revenue and does not represent customer profit or lifetime value because product costs, marketing costs, and other customer-level expenses are not available.

In [ ]:
customer_type_order_summary = (
    customer_orders
    .groupby("customer_type")
    .agg(
        customers=("customer_unique_id", "count"),
        total_orders=("orders", "sum"),
        average_orders_per_customer=("orders", "mean")
    )
    .reset_index()
)

customer_type_order_summary

## 14.7 Customer Order Frequency Findings

The comparison of order frequency shows that repeat customers generated substantially more orders per customer than one-time customers.

- One-time customers averaged **1.00 order per customer**.
- Repeat customers averaged **2.11 orders per customer**.
- The 2,913 repeat customers generated **6,159 orders** in total.

Combined with the customer revenue analysis, repeat customers also generated higher average item revenue per customer.

These findings suggest that repeat purchasing is associated with greater customer-level revenue contribution in the Olist dataset. However, the analysis does not establish causation or measure customer profitability.

## 14.8 Customer Segmentation by Order Frequency

Customers will be segmented according to their observed order frequency.

The segmentation is designed to distinguish one-time customers from increasingly active repeat customers:

- **One-Time:** 1 order
- **Occasional:** 2 orders
- **Repeat:** 3–4 orders
- **Highly Active:** 5 or more orders

These segments are descriptive and are based only on observed purchase frequency in the dataset.

In [ ]:
def customer_segment(order_count):
    if order_count == 1:
        return "One-Time"
    elif order_count == 2:
        return "Occasional"
    elif order_count <= 4:
        return "Repeat"
    else:
        return "Highly Active"


customer_orders["customer_segment"] = (
    customer_orders["orders"].apply(customer_segment)
)

customer_segments = (
    customer_orders
    .groupby("customer_segment")
    .agg(
        customers=("customer_unique_id", "count"),
        orders=("orders", "sum"),
        revenue=("revenue", "sum")
    )
    .reset_index()
)

customer_segments["customer_share_pct"] = (
    customer_segments["customers"] /
    customer_segments["customers"].sum()
) * 100

customer_segments["revenue_share_pct"] = (
    customer_segments["revenue"] /
    customer_segments["revenue"].sum()
) * 100

customer_segments["revenue_per_customer"] = (
    customer_segments["revenue"] /
    customer_segments["customers"]
)

customer_segments

## 14.9 Customer Segment Findings

The customer segmentation shows a clear relationship between purchase frequency and item revenue per customer.

- **One-Time customers:** 92,507 customers with an average item revenue of **138.67** per customer.
- **Occasional customers:** 2,673 customers with an average item revenue of **247.70** per customer.
- **Repeat customers:** 221 customers with an average item revenue of **402.57** per customer.
- **Highly Active customers:** 19 customers with an average item revenue of **643.56** per customer.

Revenue per customer increases across the observed purchase-frequency segments.

The finding indicates that customers with higher purchase frequency contributed more item revenue per customer within the Olist dataset. This is an association rather than a causal relationship, and the analysis does not measure profitability or customer lifetime value.

In [ ]:
print("CUSTOMER SEGMENT VALIDATION")
print("=" * 45)

print(
    "Total customers:",
    customer_segments["customers"].sum()
)

print(
    "Total orders:",
    customer_segments["orders"].sum()
)

print(
    "Total revenue:",
    round(customer_segments["revenue"].sum(), 2)
)

print("\nExpected:")
print("Customers:", customer_orders["customer_unique_id"].nunique())
print("Orders:", customer_orders["orders"].sum())
print("Revenue:", round(customer_orders["revenue"].sum(), 2))

## 14.10 Customer Segmentation Validation

The customer segmentation was validated against the original customer-level analysis.

The totals reconcile exactly:

- **95,420** unique customers
- **98,666** orders
- **13,591,643.70** total item revenue

No customers, orders, or revenue were lost or duplicated during segmentation.

The customer segmentation is therefore ready for further behavioral analysis.

## 14.11 Customer Recency Analysis

Customer recency measures how recently each customer placed an order relative to the latest purchase date available in the dataset.

The most recent purchase date in the dataset will be used as the reference date. This avoids using the current calendar date, which would incorrectly make all historical customers appear inactive.

Recency will be measured in days:

**Recency = Reference Date − Customer's Most Recent Order Date**

A lower recency value indicates a more recent purchase.

In [ ]:
reference_date = order_item_analysis[
    "order_purchase_timestamp"
].max().normalize()

customer_recency = (
    order_item_analysis
    .groupby("customer_unique_id")
    .agg(
        last_purchase_date=("order_purchase_timestamp", "max")
    )
    .reset_index()
)

customer_recency["recency_days"] = (
    reference_date -
    customer_recency["last_purchase_date"].dt.normalize()
).dt.days

print("CUSTOMER RECENCY")
print("=" * 45)

print("Reference date:", reference_date)
print("Customers analyzed:", customer_recency["customer_unique_id"].nunique())

print("\nRecency statistics:")
print(
    customer_recency["recency_days"].describe()
)

## 14.12 Customer Recency Findings

The customer recency analysis uses **September 3, 2018** as the reference date because it is the latest purchase date available in the dataset.

Key findings:

- **95,420 customers** were included in the recency analysis.
- The average recency was **243.50 days**.
- The median recency was **224 days**.
- 25% of customers had made their most recent purchase within **119 days** of the reference date.
- 75% of customers had made their most recent purchase within **353 days**.
- The maximum observed recency was **729 days**.

The median is useful for understanding the typical customer because the distribution spans a wide range of historical purchase dates.

These values describe historical customer behavior in the Olist dataset and should not be interpreted as current customer activity.

## 14.13 Customer Recency Segmentation

Customers will be grouped into four recency segments using the observed quartiles of the recency distribution.

The segments are:

- **Very Recent:** 0–119 days
- **Recent:** 120–224 days
- **Less Recent:** 225–353 days
- **Distant:** More than 353 days

These thresholds are derived from the dataset's observed 25th, 50th, and 75th percentiles rather than being externally defined benchmarks.

In [ ]:
customer_recency["recency_segment"] = pd.cut(
    customer_recency["recency_days"],
    bins=[-1, 119, 224, 353, float("inf")],
    labels=[
        "Very Recent",
        "Recent",
        "Less Recent",
        "Distant"
    ]
)

recency_segments = (
    customer_recency
    .groupby("recency_segment", observed=False)
    .agg(
        customers=("customer_unique_id", "count"),
        average_recency_days=("recency_days", "mean")
    )
    .reset_index()
)

recency_segments["customer_share_pct"] = (
    recency_segments["customers"] /
    recency_segments["customers"].sum()
) * 100

recency_segments

## 14.14 Customer Recency Findings

The quartile-based recency segmentation divides the **95,420 customers** into four approximately equal-sized groups.

- **Very Recent:** 23,894 customers (25.04%), with an average recency of **62.40 days**.
- **Recent:** 23,944 customers (25.09%), with an average recency of **171.84 days**.
- **Less Recent:** 23,849 customers (24.99%), with an average recency of **283.16 days**.
- **Distant:** 23,733 customers (24.87%), with an average recency of **458.27 days**.

The relatively even customer distribution confirms that the segments were created using the observed quartiles of the dataset.

These segments describe relative purchase recency within the historical Olist dataset and do not represent current customer activity.

## 14.15 Creating the Customer RFM Base

Recency and purchase-frequency measures will be combined with customer revenue to create a customer-level analytical dataset.

The three dimensions are:

- **Recency:** Days since the customer's most recent purchase.
- **Frequency:** Number of distinct orders placed by the customer.
- **Monetary Value:** Total item revenue generated by the customer.

This creates an RFM-style analytical foundation for understanding different customer behaviors.

The monetary measure represents item revenue and should not be interpreted as profit or customer lifetime value.

In [ ]:
customer_rfm = (
    customer_orders[
        [
            "customer_unique_id",
            "orders",
            "revenue",
            "customer_segment"
        ]
    ]
    .merge(
        customer_recency[
            [
                "customer_unique_id",
                "last_purchase_date",
                "recency_days",
                "recency_segment"
            ]
        ],
        on="customer_unique_id",
        how="left"
    )
)

print("CUSTOMER RFM BASE")
print("=" * 45)

print("Rows:", len(customer_rfm))
print(
    "Unique customers:",
    customer_rfm["customer_unique_id"].nunique()
)

print("\nMissing values:")
print(
    customer_rfm[
        [
            "orders",
            "revenue",
            "last_purchase_date",
            "recency_days"
        ]
    ].isnull().sum()
)

customer_rfm.head()

## 14.16 RFM Base Validation

The customer RFM base was validated after combining purchase frequency, revenue, and recency information.

The validation confirms:

- **95,420 unique customers** are represented.
- Each customer appears exactly once.
- There are no missing values in orders, revenue, last purchase date, or recency.
- Customer frequency and recency segments were successfully combined.
- The resulting dataset is suitable for further RFM-style analysis.

The RFM base therefore provides a consistent customer-level foundation for segmentation.

## 14.17 RFM Distribution Analysis

Before creating RFM scores, the distributions of recency, frequency, and monetary value will be examined.

This helps identify the typical customer behavior, the range of values, and potential extreme customers.

The analysis will use:

- **Recency:** Days since the customer's last purchase.
- **Frequency:** Number of distinct orders.
- **Monetary:** Total item revenue per customer.

These measures describe customer behavior within the historical Olist dataset.

In [ ]:
print("RFM DISTRIBUTION")
print("=" * 50)

print("\nRecency:")
print(customer_rfm["recency_days"].describe())

print("\nFrequency:")
print(customer_rfm["orders"].describe())

print("\nMonetary Revenue:")
print(customer_rfm["revenue"].describe())

## 14.18 RFM Scoring Method

RFM scores will be created to compare customers across three dimensions:

- **Recency (R):** More recent purchases receive higher scores.
- **Frequency (F):** Customers with more orders receive higher scores.
- **Monetary (M):** Customers generating higher item revenue receive higher scores.

Different scoring approaches are used because the three variables have different distributions.

### Recency Scoring

Recency will use the observed quartiles:

- 1 = Distant
- 2 = Less Recent
- 3 = Recent
- 4 = Very Recent

A higher Recency score therefore represents more recent customer activity.

### Frequency Scoring

Frequency is highly concentrated because most customers placed only one order.

Therefore, fixed purchase-frequency groups will be used:

- 1 order → Score 1
- 2 orders → Score 2
- 3 orders → Score 3
- 4 orders → Score 4
- 5 or more orders → Score 5

### Monetary Scoring

Monetary value will be scored using revenue quintiles so that customers are divided according to their relative revenue contribution.

- Lowest 20% → Score 1
- Next 20% → Score 2
- Middle 20% → Score 3
- Next 20% → Score 4
- Highest 20% → Score 5

The scores are relative to the observed Olist customer distribution and should not be interpreted as industry benchmarks.

In [ ]:
# Recency score
recency_score_map = {
    "Distant": 1,
    "Less Recent": 2,
    "Recent": 3,
    "Very Recent": 4
}

customer_rfm["R_score"] = (
    customer_rfm["recency_segment"]
    .map(recency_score_map)
    .astype(int)
)


# Frequency score
def frequency_score(order_count):
    if order_count == 1:
        return 1
    elif order_count == 2:
        return 2
    elif order_count == 3:
        return 3
    elif order_count == 4:
        return 4
    else:
        return 5


customer_rfm["F_score"] = (
    customer_rfm["orders"]
    .apply(frequency_score)
)


# Monetary score
customer_rfm["M_score"] = pd.qcut(
    customer_rfm["revenue"],
    q=5,
    labels=[1, 2, 3, 4, 5]
).astype(int)


print("RFM SCORE VALIDATION")
print("=" * 50)

print("\nRecency scores:")
print(customer_rfm["R_score"].value_counts().sort_index())

print("\nFrequency scores:")
print(customer_rfm["F_score"].value_counts().sort_index())

print("\nMonetary scores:")
print(customer_rfm["M_score"].value_counts().sort_index())

## 14.20 RFM Score Validation

The RFM scoring results were reviewed before creating customer segments.

### Recency

The four Recency scores contain approximately one-quarter of customers each, consistent with the quartile-based segmentation.

- Score 1: 23,733 customers
- Score 2: 23,849 customers
- Score 3: 23,944 customers
- Score 4: 23,894 customers

### Frequency

Frequency is highly concentrated:

- Score 1: 92,507 customers
- Score 2: 2,673 customers
- Score 3: 192 customers
- Score 4: 29 customers
- Score 5: 19 customers

This confirms that most customers placed only one order.

### Monetary

The monetary scores divide customers into approximately five revenue groups:

- Score 1: 19,728 customers
- Score 2: 19,815 customers
- Score 3: 17,792 customers
- Score 4: 19,051 customers
- Score 5: 19,034 customers

The slight differences between groups are expected because multiple customers can have the same revenue value, causing some quantile boundaries to contain similar values.

The scoring system is therefore suitable for creating an RFM-based customer segmentation.

## 14.21 Creating the RFM Score

The individual Recency, Frequency, and Monetary scores will be combined into a three-digit RFM score.

The score follows the format:

**RFM = Recency + Frequency + Monetary**

For example:

- `415` = very recent purchase, one order, high monetary value
- `154` = distant purchase, one order, high monetary value
- `555` = very recent, highly frequent, high monetary value

The three individual scores will be retained alongside the combined RFM score so that customer behavior can be interpreted across all dimensions.m

In [ ]:
customer_rfm["RFM_score"] = (
    customer_rfm["R_score"].astype(str) +
    customer_rfm["F_score"].astype(str) +
    customer_rfm["M_score"].astype(str)
)

print("RFM SCORE SAMPLE")
print("=" * 50)

print(
    customer_rfm[
        [
            "customer_unique_id",
            "recency_days",
            "orders",
            "revenue",
            "R_score",
            "F_score",
            "M_score",
            "RFM_score"
        ]
    ].head(10)
)

print("\nUnique RFM scores:", customer_rfm["RFM_score"].nunique())

## 14.22 RFM Customer Segmentation

The individual RFM scores will be converted into descriptive customer segments.

The segmentation uses the customer's Recency, Frequency, and Monetary scores together.

The segments are designed to describe observed customer behavior rather than assign a subjective ranking to customers.

The following rules will be used:

- **High Value:** High recency, frequency, and monetary scores.
- **Recent Customers:** High recency score but lower frequency.
- **Repeat Customers:** Higher frequency score indicating multiple purchases.
- **High Spending:** High monetary score with lower or moderate frequency.
- **Low Engagement:** Low recency score combined with low frequency.
- **Other:** Customers whose RFM combination does not fall into the above descriptive groups.

The original RFM scores will be retained so the segmentation rules remain transparent.

In [ ]:
def assign_rfm_segment(row):
    r = row["R_score"]
    f = row["F_score"]
    m = row["M_score"]

    if r >= 3 and f >= 3 and m >= 3:
        return "High Value"

    elif r >= 3 and f <= 2:
        return "Recent Customers"

    elif f >= 3:
        return "Repeat Customers"

    elif m >= 4:
        return "High Spending"

    elif r <= 2 and f <= 2:
        return "Low Engagement"

    else:
        return "Other"


customer_rfm["rfm_segment"] = (
    customer_rfm.apply(assign_rfm_segment, axis=1)
)

rfm_segments = (
    customer_rfm
    .groupby("rfm_segment")
    .agg(
        customers=("customer_unique_id", "count"),
        average_recency=("recency_days", "mean"),
        average_orders=("orders", "mean"),
        total_revenue=("revenue", "sum"),
        average_revenue=("revenue", "mean")
    )
    .reset_index()
)

rfm_segments["customer_share_pct"] = (
    rfm_segments["customers"] /
    rfm_segments["customers"].sum()
) * 100

rfm_segments

## 14.23 RFM Segment Validation

The RFM segments will be validated against the complete customer RFM dataset.

The validation will confirm that:

- Every customer belongs to exactly one RFM segment.
- The total number of customers remains **95,420**.
- Total item revenue remains **13,591,643.70**.
- No customers or revenue were lost during segmentation.

This ensures that the segmentation does not introduce duplication or exclude customers.

In [ ]:
print("RFM SEGMENT VALIDATION")
print("=" * 50)

print(
    "Total customers in segments:",
    rfm_segments["customers"].sum()
)

print(
    "Expected customers:",
    customer_rfm["customer_unique_id"].nunique()
)

print(
    "Total revenue in segments:",
    round(rfm_segments["total_revenue"].sum(), 2)
)

print(
    "Expected revenue:",
    round(customer_rfm["revenue"].sum(), 2)
)

print(
    "Customers without segment:",
    customer_rfm["rfm_segment"].isna().sum()
)

print(
    "Unique customers in RFM table:",
    customer_rfm["customer_unique_id"].nunique()
)

## 14.24 RFM Segment Findings

The RFM segmentation provides a descriptive view of customer purchasing behavior in the Olist dataset.

Key findings:

- **Recent Customers** are the largest segment, containing **47,687 customers (49.98%)**. Their average recency is approximately **117 days**, and they average **1.03 orders** per customer.
- **Low Engagement** contains **29,028 customers (30.42%)**. These customers have an average recency of approximately **371 days** and generate an average of **56.23** in item revenue per customer.
- **High Spending** contains **18,465 customers (19.35%)** and generates approximately **5.09 million** in total item revenue. Their average item revenue is **275.73** per customer.
- **High Value** contains **150 customers (0.16%)**. These customers have an average of **3.53 orders** and **448.33** in item revenue per customer.
- **Repeat Customers** contains **90 customers (0.09%)**, with an average of **3.14 orders** and **377.18** in item revenue per customer.

The segmentation shows that customer recency, purchase frequency, and monetary contribution vary substantially across the observed customer base.

Because the segmentation is based on historical Olist data, these groups describe observed behavior in this dataset and should not be interpreted as current customer status or industry benchmarks.

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.bar(
    rfm_segments["rfm_segment"],
    rfm_segments["customers"]
)

plt.title("Customer Distribution by RFM Segment")
plt.xlabel("RFM Segment")
plt.ylabel("Number of Customers")
plt.xticks(rotation=30)
plt.tight_layout()

plt.show()

## 14.25 RFM Segment Revenue Contribution

Customer count shows the size of each RFM segment, but revenue contribution shows the economic contribution of each segment.

The analysis will compare:

- Total item revenue by RFM segment
- Revenue share of each segment
- Average revenue per customer

This helps identify which customer groups contribute the largest share of marketplace revenue.

Revenue represents item sales revenue and does not represent profit or customer lifetime value.

In [ ]:
rfm_revenue_summary = (
    customer_rfm
    .groupby("rfm_segment")
    .agg(
        customers=("customer_unique_id", "count"),
        total_revenue=("revenue", "sum"),
        average_revenue=("revenue", "mean"),
        average_orders=("orders", "mean"),
        average_recency=("recency_days", "mean")
    )
    .reset_index()
)

rfm_revenue_summary["customer_share_pct"] = (
    rfm_revenue_summary["customers"]
    / rfm_revenue_summary["customers"].sum()
) * 100

rfm_revenue_summary["revenue_share_pct"] = (
    rfm_revenue_summary["total_revenue"]
    / rfm_revenue_summary["total_revenue"].sum()
) * 100

rfm_revenue_summary = rfm_revenue_summary.sort_values(
    "total_revenue",
    ascending=False
)

rfm_revenue_summary

In [ ]:
rfm_revenue_summary = (
    customer_rfm
    .groupby("rfm_segment")
    .agg(
        customers=("customer_unique_id", "count"),
        total_revenue=("revenue", "sum"),
        average_revenue=("revenue", "mean"),
        average_orders=("orders", "mean"),
        average_recency=("recency_days", "mean")
    )
    .reset_index()
)

rfm_revenue_summary["customer_share_pct"] = (
    rfm_revenue_summary["customers"]
    / rfm_revenue_summary["customers"].sum()
) * 100

rfm_revenue_summary["revenue_share_pct"] = (
    rfm_revenue_summary["total_revenue"]
    / rfm_revenue_summary["total_revenue"].sum()
) * 100

rfm_revenue_summary = rfm_revenue_summary.sort_values(
    "total_revenue",
    ascending=False
)

rfm_revenue_summary

## 14.26 RFM Revenue Contribution Findings

The RFM revenue analysis compares the size of each customer segment with its contribution to total item revenue.

Key findings:

- **Recent Customers** represent **49.98%** of customers and contribute **49.79%** of total item revenue. This segment contains the largest share of the customer base and contributes a similar share of revenue.
- **High Spending** customers represent only **19.35%** of customers but contribute **37.46%** of total item revenue. Their average item revenue is **275.73** per customer.
- **Low Engagement** customers represent **30.42%** of customers but contribute only **12.01%** of total item revenue. Their average item revenue is **56.23** per customer.
- **High Value** customers represent **0.16%** of customers and contribute **0.49%** of total item revenue, with an average of **3.53 orders** per customer.
- **Repeat Customers** represent **0.09%** of customers and contribute **0.25%** of total item revenue, with an average of **3.14 orders** per customer.

The largest difference between customer share and revenue share occurs in the **High Spending** segment, which contributes a substantially larger share of revenue than its share of customers.

These results describe historical item-revenue contribution within the Olist dataset. They do not measure profitability, customer lifetime value, or future customer behavior.

# 15. Customer Geographic Analysis

Customer geography will be analyzed using the customer's state information.

The analysis will examine:

- Number of customers by state
- Number of orders by state
- Item revenue by state
- Average revenue per customer

This analysis can identify geographic concentrations in the marketplace and compare customer volume with revenue contribution.

The analysis describes the historical Olist dataset and does not represent current geographic demand.

In [ ]:
state_analysis = (
    order_item_analysis
    .groupby("customer_state")
    .agg(
        customers=("customer_unique_id", "nunique"),
        orders=("order_id", "nunique"),
        revenue=("price", "sum")
    )
    .reset_index()
)

state_analysis["average_revenue_per_customer"] = (
    state_analysis["revenue"] /
    state_analysis["customers"]
)

state_analysis = state_analysis.sort_values(
    "revenue",
    ascending=False
)

state_analysis.head(10)

## 15.1 Geographic Revenue Findings

The state-level analysis shows that customer activity is concentrated in a small number of Brazilian states.

Key findings:

- **São Paulo (SP)** has the largest customer base with **39,981 customers** and generates **5,202,955.05** in item revenue.
- **Rio de Janeiro (RJ)** is the second-largest market with **12,303 customers** and **1,824,092.67** in item revenue.
- **Minas Gerais (MG)** has **11,178 customers** and generates **1,585,308.03** in item revenue.
- **Rio Grande do Sul (RS)** and **Paraná (PR)** are also among the larger markets by customer and order volume.
- **Bahia (BA)** has an average revenue per customer of **157.00**, which is higher than São Paulo's **130.14**, despite having a much smaller customer base.
- **Goiás (GO)** also has a relatively high average revenue per customer of **151.70**.

The results demonstrate that geographic market size and average revenue per customer are different dimensions. A state can have a smaller customer base while generating relatively higher revenue per customer.

These findings describe the historical Olist dataset and should not be interpreted as current Brazilian e-commerce market statistics.

## 15.2 Geographic Revenue Concentration

Revenue concentration will be calculated to determine the proportion of total item revenue generated by the largest customer markets.

The analysis will calculate:

- Revenue share by state
- Cumulative revenue share
- Revenue contribution of the top 5 states

This provides a clearer view of geographic concentration than revenue totals alone.

In [ ]:
state_analysis["revenue_share_pct"] = (
    state_analysis["revenue"] /
    state_analysis["revenue"].sum()
) * 100

state_analysis["cumulative_revenue_share_pct"] = (
    state_analysis["revenue_share_pct"]
    .cumsum()
)

print("TOP 10 STATES BY REVENUE")
print("=" * 55)

print(
    state_analysis[
        [
            "customer_state",
            "customers",
            "orders",
            "revenue",
            "revenue_share_pct",
            "cumulative_revenue_share_pct"
        ]
    ].head(10)
)

print(
    "\nTop 5 states revenue share:",
    round(
        state_analysis.head(5)["revenue_share_pct"].sum(),
        2
    ),
    "%"
)

## 15.3 Geographic Revenue Concentration Findings

The geographic concentration analysis shows that item revenue is heavily concentrated among a small number of Brazilian states.

Key findings:

- **São Paulo (SP)** contributes **38.28%** of total item revenue.
- **Rio de Janeiro (RJ)** contributes **13.42%**.
- **Minas Gerais (MG)** contributes **11.66%**.
- **Rio Grande do Sul (RS)** contributes **5.52%**.
- **Paraná (PR)** contributes **5.03%**.
- Together, these **top 5 states contribute 73.91% of total item revenue**.

The remaining states collectively contribute approximately **26.09%**.

São Paulo alone contributes more than one-third of total item revenue in the dataset, demonstrating a substantial geographic concentration of marketplace activity.

This concentration reflects the historical Olist dataset and should not be interpreted as a current market-share estimate for Brazilian e-commerce.

In [ ]:
top_10_states = state_analysis.head(10).sort_values(
    "revenue",
    ascending=True
)

plt.figure(figsize=(10, 6))

plt.barh(
    top_10_states["customer_state"],
    top_10_states["revenue"]
)

plt.title("Top 10 States by Item Revenue")
plt.xlabel("Item Revenue")
plt.ylabel("State")
plt.tight_layout()

plt.show()

# 16. Seller Performance Analysis

Seller-level analysis will be used to evaluate marketplace supply-side performance.

The analysis will examine:

- Number of sellers
- Orders handled by each seller
- Items sold
- Item revenue
- Average item price
- Seller revenue concentration

Seller performance will be measured using the order-item dataset.

Revenue represents item sales revenue and does not represent seller profit because seller costs and margins are not available in the dataset.

In [ ]:
seller_analysis = (
    order_item_analysis
    .groupby("seller_id")
    .agg(
        orders=("order_id", "nunique"),
        items_sold=("product_id", "count"),
        revenue=("price", "sum"),
        average_item_price=("price", "mean")
    )
    .reset_index()
)

seller_analysis["revenue_share_pct"] = (
    seller_analysis["revenue"] /
    seller_analysis["revenue"].sum()
) * 100

seller_analysis = seller_analysis.sort_values(
    "revenue",
    ascending=False
)

print("SELLER PERFORMANCE OVERVIEW")
print("=" * 50)

print("Unique sellers:", seller_analysis["seller_id"].nunique())
print("Total orders:", seller_analysis["orders"].sum())
print("Total items sold:", seller_analysis["items_sold"].sum())
print("Total item revenue:", round(seller_analysis["revenue"].sum(), 2))

print("\nTop 10 sellers by revenue:")
seller_analysis.head(10)

## 16.2 Seller Revenue Concentration

Seller revenue concentration will be analyzed to determine how much of marketplace item revenue is generated by the largest sellers.

The analysis will calculate:

- Revenue share by seller
- Cumulative revenue share
- Revenue contribution of the top 5, 10, and 20 sellers

This helps identify whether marketplace revenue is broadly distributed across sellers or concentrated among a smaller group.

Revenue concentration does not indicate seller profitability because product costs and seller margins are not available in the dataset.

In [ ]:
seller_analysis["cumulative_revenue_share_pct"] = (
    seller_analysis["revenue_share_pct"]
    .cumsum()
)

top_5_seller_share = seller_analysis.head(5)["revenue_share_pct"].sum()
top_10_seller_share = seller_analysis.head(10)["revenue_share_pct"].sum()
top_20_seller_share = seller_analysis.head(20)["revenue_share_pct"].sum()

print("SELLER REVENUE CONCENTRATION")
print("=" * 50)

print(f"Top 5 sellers revenue share: {top_5_seller_share:.2f}%")
print(f"Top 10 sellers revenue share: {top_10_seller_share:.2f}%")
print(f"Top 20 sellers revenue share: {top_20_seller_share:.2f}%")

print("\nTop 10 sellers:")
print(
    seller_analysis[
        [
            "seller_id",
            "orders",
            "items_sold",
            "revenue",
            "revenue_share_pct",
            "cumulative_revenue_share_pct"
        ]
    ].head(10)
)

## 16.3 Seller Revenue Concentration Findings

The seller concentration analysis shows that marketplace item revenue is distributed across a relatively large number of sellers.

Key findings:

- The **top 5 sellers** contribute **7.61%** of total item revenue.
- The **top 10 sellers** contribute **13.15%**.
- The **top 20 sellers** contribute **21.09%**.
- The remaining sellers collectively contribute **78.91%** of item revenue.

The largest individual seller contributes only **1.69%** of total item revenue.

This indicates that the marketplace's historical item revenue was not dependent on a small group of sellers. Revenue was distributed across a broader seller base.

This analysis measures revenue concentration only. It does not evaluate seller profitability, seller quality, or operational performance because cost and margin information is not available.

In [ ]:
top_10_sellers = seller_analysis.head(10).copy()

top_10_sellers = top_10_sellers.sort_values(
    "revenue",
    ascending=True
)

plt.figure(figsize=(10, 6))

plt.barh(
    top_10_sellers["seller_id"],
    top_10_sellers["revenue"]
)

plt.title("Top 10 Sellers by Item Revenue")
plt.xlabel("Item Revenue")
plt.ylabel("Seller ID")

plt.tight_layout()
plt.show()

## 16.5 Seller Volume vs Revenue

Seller revenue can be generated through different combinations of sales volume and item price.

A seller may generate high revenue by:

- Selling a large number of items
- Selling fewer items at higher prices
- Combining high volume with relatively high item prices

Therefore, seller item volume and revenue will be compared to identify differences in seller sales strategies.

In [ ]:
seller_volume_revenue = seller_analysis[
    [
        "seller_id",
        "items_sold",
        "revenue",
        "average_item_price"
    ]
].copy()

seller_volume_revenue["revenue_per_item"] = (
    seller_volume_revenue["revenue"] /
    seller_volume_revenue["items_sold"]
)

print("SELLER VOLUME VS REVENUE")
print("=" * 50)

print(
    seller_volume_revenue.sort_values(
        "items_sold",
        ascending=False
    ).head(10)
)

## 16.6 Seller Volume vs Revenue Findings

The comparison between seller volume and revenue shows that item volume alone does not determine seller revenue.

Key observations:

- Seller `6560211a19b47992c3666cc44a7e94c0` sold the highest number of items among the sellers shown, with **2,033 items**, but generated **123,304.83** in item revenue.
- Seller `4a3ca9315b744ce9f8e9374361493884` sold **1,987 items** and generated **200,472.92**, substantially higher revenue than the highest-volume seller.
- Seller `7c67e1448b00f6e969d365cea6b010ab` sold **1,364 items** but generated **187,923.89**, supported by an average item price of **137.77**.
- Seller `ea8482cd71df3c1969d7b9473ff13abc` sold **1,203 items** but generated only **37,177.52**, reflecting a much lower average item price of **30.90**.

These examples demonstrate that seller revenue depends on both sales volume and average item price.

The analysis does not measure seller profitability because product costs, commissions, and margins are not available in the dataset.

In [ ]:
plt.figure(figsize=(10, 6))

plt.scatter(
    seller_volume_revenue["items_sold"],
    seller_volume_revenue["revenue"]
)

plt.title("Seller Item Volume vs Revenue")
plt.xlabel("Items Sold")
plt.ylabel("Item Revenue")

plt.tight_layout()
plt.show()

# 17. Customer Satisfaction Analysis

Customer satisfaction will be analyzed using the Olist review dataset.

The analysis will examine:

- Review score distribution
- Average review score
- Share of positive and negative reviews
- Relationship between delivery performance and review scores
- Categories and sellers associated with different satisfaction levels

Review scores range from 1 to 5, where higher scores represent more positive customer ratings.

Because some orders have multiple review records, review-level analysis will be performed carefully to avoid duplicating order-level metrics.

In [ ]:
review_score_analysis = (
    order_reviews_clean
    .groupby("review_score")
    .agg(
        reviews=("review_id", "count"),
        orders=("order_id", "nunique")
    )
    .reset_index()
)

review_score_analysis["review_share_pct"] = (
    review_score_analysis["reviews"] /
    review_score_analysis["reviews"].sum()
) * 100

average_review_score = order_reviews_clean["review_score"].mean()

print("CUSTOMER REVIEW OVERVIEW")
print("=" * 45)

print(f"Average review score: {average_review_score:.2f}")
print(f"Total review records: {len(order_reviews_clean):,}")
print(f"Unique orders reviewed: {order_reviews_clean['order_id'].nunique():,}")

print("\nReview score distribution:")
print(review_score_analysis)

## 17.2 Customer Satisfaction Findings

The review analysis shows an overall positive review distribution in the historical Olist dataset.

Key findings:

- The average review score is **4.09 out of 5**.
- **5-star reviews** account for **57.78%** of all review records.
- **4-star reviews** account for **19.29%**.
- **3-star reviews** account for **8.24%**.
- **2-star reviews** account for **3.18%**.
- **1-star reviews** account for **11.51%**.

Overall, **77.07%** of review records are rated 4 or 5 stars, while **14.69%** are rated 1 or 2 stars.

The relatively large difference between positive and negative review shares provides a useful baseline for investigating what factors are associated with lower customer satisfaction.

These results describe review records in the historical Olist dataset and should not be interpreted as a current customer-satisfaction benchmark.

In [ ]:
positive_reviews = (
    order_reviews_clean["review_score"] >= 4
).sum()

negative_reviews = (
    order_reviews_clean["review_score"] <= 2
).sum()

neutral_reviews = (
    order_reviews_clean["review_score"] == 3
).sum()

total_reviews = len(order_reviews_clean)

positive_rate = (positive_reviews / total_reviews) * 100
negative_rate = (negative_reviews / total_reviews) * 100
neutral_rate = (neutral_reviews / total_reviews) * 100

print("CUSTOMER SATISFACTION KPIs")
print("=" * 45)

print(f"Positive reviews (4-5): {positive_reviews:,} ({positive_rate:.2f}%)")
print(f"Neutral reviews (3): {neutral_reviews:,} ({neutral_rate:.2f}%)")
print(f"Negative reviews (1-2): {negative_reviews:,} ({negative_rate:.2f}%)")

## 17.4 Delivery Performance vs Customer Satisfaction

The relationship between delivery performance and customer satisfaction will be investigated by comparing delivery status with review scores.

The analysis will compare:

- Average review score for early deliveries
- Average review score for on-time deliveries
- Average review score for late deliveries
- Positive review rate for each delivery-status group

Only orders with both valid delivery-performance data and review records will be included.

Because some orders have multiple reviews, review records will be aggregated at the order level before joining them with delivery data. This prevents orders with multiple reviews from being counted multiple times in the delivery analysis.

In [ ]:
# Aggregate reviews to one record per order
order_review_summary = (
    order_reviews_clean
    .groupby("order_id")
    .agg(
        average_review_score=("review_score", "mean"),
        review_count=("review_score", "count")
    )
    .reset_index()
)

# Join delivery status with order-level review information
delivery_review_analysis = (
    delivery_analysis[
        [
            "order_id",
            "delivery_status",
            "delivery_delay_days"
        ]
    ]
    .merge(
        order_review_summary,
        on="order_id",
        how="inner"
    )
)

# Positive review indicator
delivery_review_analysis["positive_review"] = (
    delivery_review_analysis["average_review_score"] >= 4
)

delivery_review_summary = (
    delivery_review_analysis
    .groupby("delivery_status")
    .agg(
        orders=("order_id", "count"),
        average_review_score=("average_review_score", "mean"),
        positive_reviews=("positive_review", "sum")
    )
    .reset_index()
)

delivery_review_summary["positive_review_rate_pct"] = (
    delivery_review_summary["positive_reviews"] /
    delivery_review_summary["orders"]
) * 100

delivery_review_summary

## 17.5 Delivery and Customer Satisfaction Findings

The comparison between delivery performance and customer reviews shows a substantial difference in customer satisfaction across delivery-status groups.

Key findings:

- **Early deliveries** had an average review score of **4.29**, with **82.77%** of reviews classified as positive.
- **On-time deliveries** had an average review score of **4.04**, with **73.59%** classified as positive.
- **Late deliveries** had an average review score of only **2.27**, with **26.72%** classified as positive.
- The late-delivery group therefore shows a substantially lower average review score and positive-review rate than the early-delivery group.

The results indicate a strong association between late delivery and lower customer review scores in the analyzed Olist data.

However, this analysis does not establish that late delivery alone causes lower ratings. Other factors such as product quality, seller performance, payment experience, or customer expectations may also influence review scores.

The analysis uses orders with both valid delivery information and review records, with reviews aggregated to the order level before joining.

In [ ]:
plt.figure(figsize=(9, 5))

plt.bar(
    delivery_review_summary["delivery_status"],
    delivery_review_summary["average_review_score"]
)

plt.title("Average Review Score by Delivery Status")
plt.xlabel("Delivery Status")
plt.ylabel("Average Review Score")

plt.ylim(0, 5)
plt.tight_layout()

plt.show()

### 17.6 Delivery Status and Review Score Visualization

The visualization highlights the difference in average customer review scores across delivery-status groups.

Late deliveries have a substantially lower average review score than early and on-time deliveries. This supports the earlier finding that delivery performance is strongly associated with customer satisfaction in the analyzed Olist dataset.

## 17.7 Delay Severity vs Customer Satisfaction

The previous analysis showed a substantial difference between late and non-late deliveries.

This analysis will examine whether the severity of a delay is also associated with customer satisfaction.

Late orders will be grouped into delay ranges:

- 1–3 days late
- 4–7 days late
- 8–14 days late
- 15–30 days late
- More than 30 days late

The average review score and positive-review rate will then be calculated for each delay group.

Only orders with valid delivery and review information will be included.

In [ ]:
late_review_analysis = delivery_review_analysis[
    delivery_review_analysis["delivery_delay_days"] > 0
].copy()

late_review_analysis["delay_group"] = pd.cut(
    late_review_analysis["delivery_delay_days"],
    bins=[0, 3, 7, 14, 30, float("inf")],
    labels=[
        "1–3 days",
        "4–7 days",
        "8–14 days",
        "15–30 days",
        "30+ days"
    ]
)

delay_review_summary = (
    late_review_analysis
    .groupby("delay_group", observed=True)
    .agg(
        orders=("order_id", "count"),
        average_review_score=("average_review_score", "mean"),
        positive_reviews=("positive_review", "sum")
    )
    .reset_index()
)

delay_review_summary["positive_review_rate_pct"] = (
    delay_review_summary["positive_reviews"] /
    delay_review_summary["orders"]
) * 100

delay_review_summary

## 17.8 Delay Severity and Customer Satisfaction Findings

The delay-severity analysis shows a strong association between moderate-to-severe delivery delays and lower customer satisfaction.

Key findings:

- Orders delayed **1–3 days** had an average review score of **3.29**, with **53.24%** positive reviews.
- Orders delayed **4–7 days** had an average score of **2.10**, with **22.44%** positive reviews.
- Orders delayed **8–14 days** had an average score of **1.67**, with only **11.07%** positive reviews.
- Orders delayed **15–30 days** had the lowest average score at **1.62**, with **9.05%** positive reviews.
- Orders delayed **more than 30 days** had an average score of **2.06**, with **23.10%** positive reviews.

The results show a substantial deterioration in customer satisfaction as delays increase from short delays into the 8–30 day range.

The 30+ day group does not continue the same downward pattern, so the results should not be interpreted as a strictly monotonic relationship between every additional delay range and review score.

The analysis identifies an association between delay severity and customer satisfaction; it does not establish causation.

In [ ]:
plt.figure(figsize=(10, 5))

plt.bar(
    delay_review_summary["delay_group"].astype(str),
    delay_review_summary["average_review_score"]
)

plt.title("Average Review Score by Delivery Delay")
plt.xlabel("Delivery Delay")
plt.ylabel("Average Review Score")

plt.ylim(0, 5)
plt.tight_layout()

plt.show()

## 17.10 Product Category and Customer Satisfaction

Customer satisfaction can vary across product categories due to differences in product expectations, quality, pricing, and purchasing experience.

The review data will therefore be combined with product-category information to compare:

- Number of reviewed orders
- Average review score
- Positive-review rate

Reviews will first be aggregated to the order level before joining with product information to avoid duplicating review metrics.

In [ ]:
# One review summary per order
order_review_summary = (
    order_reviews_clean
    .groupby("order_id")
    .agg(
        average_review_score=("review_score", "mean"),
        review_count=("review_score", "count")
    )
    .reset_index()
)

# One category per order for category-level analysis
order_category = (
    order_item_analysis[
        [
            "order_id",
            "product_category_english"
        ]
    ]
    .drop_duplicates("order_id")
)

# Join reviews with category
category_review_analysis = (
    order_review_summary
    .merge(
        order_category,
        on="order_id",
        how="inner"
    )
)

# Positive review indicator
category_review_analysis["positive_review"] = (
    category_review_analysis["average_review_score"] >= 4
)

category_review_summary = (
    category_review_analysis
    .groupby("product_category_english")
    .agg(
        orders=("order_id", "count"),
        average_review_score=("average_review_score", "mean"),
        positive_reviews=("positive_review", "sum")
    )
    .reset_index()
)

category_review_summary["positive_review_rate_pct"] = (
    category_review_summary["positive_reviews"] /
    category_review_summary["orders"]
) * 100

category_review_summary = category_review_summary.sort_values(
    "orders",
    ascending=False
)

category_review_summary.head(20)

## 17.11 Product Category Satisfaction Findings

The category-level review analysis shows differences in customer satisfaction across major product categories.

Key findings:

- **Stationery** has an average review score of **4.25** and an **82.35%** positive-review rate among 2,278 reviewed orders.
- **Pet Shop** has an average score of **4.24**, with an **81.47%** positive-review rate across 1,695 reviewed orders.
- **Perfumery** has an average score of **4.21**, with an **80.17%** positive-review rate across 3,137 reviewed orders.
- **Health & Beauty** has an average score of **4.19**, with a **79.69%** positive-review rate across 8,731 reviewed orders.
- **Bed Bath Table** has a lower average score of **3.98**, with a **73.47%** positive-review rate across 9,207 reviewed orders.
- **Office Furniture** has an average score of **3.62** and a **63.03%** positive-review rate across 1,255 reviewed orders.

Among the categories shown, Office Furniture has the lowest average review score and positive-review rate, while Stationery has the highest values.

These results identify differences in customer satisfaction across categories, but they do not establish why the differences occur. Factors such as delivery performance, product expectations, seller performance, and product characteristics may contribute to the observed results.

In [ ]:
category_review_reliable = category_review_summary[
    category_review_summary["orders"] >= 2000
].copy()

category_review_reliable = category_review_reliable.sort_values(
    "average_review_score",
    ascending=True
)

plt.figure(figsize=(10, 7))

plt.barh(
    category_review_reliable["product_category_english"],
    category_review_reliable["average_review_score"]
)

plt.title("Average Review Score by Product Category")
plt.xlabel("Average Review Score")
plt.ylabel("Product Category")

plt.xlim(0, 5)
plt.tight_layout()

plt.show()

## 17.13 Seller Performance vs Customer Satisfaction

Seller performance can influence customer satisfaction through product quality, order fulfillment, and the overall purchasing experience.

This analysis will compare seller-level performance with customer review scores.

The analysis will focus on sellers with a meaningful number of reviewed orders to avoid drawing conclusions from sellers with very few reviews.

Key metrics:

- Number of reviewed orders
- Average review score
- Positive-review rate
- Item revenue

In [ ]:
seller_review_analysis = (
    order_item_analysis[
        [
            "order_id",
            "seller_id",
            "price"
        ]
    ]
    .drop_duplicates(["order_id", "seller_id"])
    .merge(
        order_review_summary,
        on="order_id",
        how="inner"
    )
)

seller_review_summary = (
    seller_review_analysis
    .groupby("seller_id")
    .agg(
        reviewed_orders=("order_id", "nunique"),
        average_review_score=("average_review_score", "mean"),
        positive_reviews=("average_review_score", lambda x: (x >= 4).sum()),
        revenue=("price", "sum")
    )
    .reset_index()
)

seller_review_summary["positive_review_rate_pct"] = (
    seller_review_summary["positive_reviews"] /
    seller_review_summary["reviewed_orders"]
) * 100

# Focus on sellers with at least 50 reviewed orders
seller_review_reliable = seller_review_summary[
    seller_review_summary["reviewed_orders"] >= 50
].copy()

seller_review_reliable = seller_review_reliable.sort_values(
    "average_review_score",
    ascending=False
)

seller_review_reliable.head(15)

In [ ]:
seller_review_analysis = (
    order_item_analysis[
        [
            "order_id",
            "seller_id",
            "price"
        ]
    ]
    .drop_duplicates(["order_id", "seller_id"])
    .merge(
        order_review_summary,
        on="order_id",
        how="inner"
    )
)

seller_review_summary = (
    seller_review_analysis
    .groupby("seller_id")
    .agg(
        reviewed_orders=("order_id", "nunique"),
        average_review_score=("average_review_score", "mean"),
        positive_reviews=(
            "average_review_score",
            lambda x: (x >= 4).sum()
        ),
        revenue=("price", "sum")
    )
    .reset_index()
)

seller_review_summary["positive_review_rate_pct"] = (
    seller_review_summary["positive_reviews"] /
    seller_review_summary["reviewed_orders"]
) * 100

# Only include sellers with at least 50 reviewed orders
seller_review_reliable = seller_review_summary[
    seller_review_summary["reviewed_orders"] >= 50
].copy()

seller_review_reliable = seller_review_reliable.sort_values(
    "average_review_score",
    ascending=False
)

print("Sellers with 50+ reviewed orders:",
      len(seller_review_reliable))

seller_review_reliable.head(15)

In [ ]:
print("order_item_analysis exists:", "order_item_analysis" in globals())
print("order_review_summary exists:", "order_review_summary" in globals())

In [ ]:
# Recreate the order-item analysis dataset

order_item_analysis = (
    order_items_clean
    .merge(
        orders_clean,
        on="order_id",
        how="left"
    )
    .merge(
        customers_clean,
        on="customer_id",
        how="left"
    )
    .merge(
        products_clean[
            [
                "product_id",
                "product_category_name"
            ]
        ],
        on="product_id",
        how="left"
    )
    .merge(
        sellers_clean,
        on="seller_id",
        how="left"
    )
)

print("order_item_analysis created successfully")
print("Shape:", order_item_analysis.shape)

In [ ]:
# Create one review record per order

order_review_summary = (
    order_reviews_clean
    .groupby("order_id")
    .agg(
        average_review_score=("review_score", "mean"),
        review_count=("review_score", "count")
    )
    .reset_index()
)

print("order_review_summary created successfully")
print("Shape:", order_review_summary.shape)
print("Unique orders:", order_review_summary["order_id"].nunique())

order_review_summary.head()

In [ ]:
seller_review_analysis = (
    order_item_analysis[
        [
            "order_id",
            "seller_id",
            "price"
        ]
    ]
    .drop_duplicates(["order_id", "seller_id"])
    .merge(
        order_review_summary,
        on="order_id",
        how="inner"
    )
)

seller_review_summary = (
    seller_review_analysis
    .groupby("seller_id")
    .agg(
        reviewed_orders=("order_id", "nunique"),
        average_review_score=("average_review_score", "mean"),
        positive_reviews=(
            "average_review_score",
            lambda x: (x >= 4).sum()
        ),
        revenue=("price", "sum")
    )
    .reset_index()
)

seller_review_summary["positive_review_rate_pct"] = (
    seller_review_summary["positive_reviews"] /
    seller_review_summary["reviewed_orders"]
) * 100

# Keep sellers with at least 50 reviewed orders
seller_review_reliable = seller_review_summary[
    seller_review_summary["reviewed_orders"] >= 50
].copy()

seller_review_reliable = seller_review_reliable.sort_values(
    "average_review_score",
    ascending=False
)

print("SELLER CUSTOMER SATISFACTION")
print("=" * 50)

print(
    "Sellers with 50+ reviewed orders:",
    len(seller_review_reliable)
)

seller_review_reliable.head(15)

## 17.14 Seller Satisfaction — Lowest-Rated Sellers

To identify potential customer-experience issues, the same seller group will be examined from the opposite direction.

Only sellers with at least 50 reviewed orders are included to reduce the influence of very small samples.

The analysis will identify sellers with the lowest average review scores and compare their positive-review rates and revenue.

In [ ]:
lowest_rated_sellers = seller_review_reliable.sort_values(
    "average_review_score",
    ascending=True
)

print("LOWEST-RATED SELLERS")
print("=" * 50)

lowest_rated_sellers.head(15)

## 17.15 Seller Satisfaction Findings

The seller-level satisfaction analysis shows substantial variation in customer experience across sellers.

Among sellers with at least 50 reviewed orders:

- The highest-rated seller had an average review score of **4.82** and a **97.01% positive-review rate** across 67 reviewed orders.
- The lowest-rated seller had an average review score of only **2.33** and a **28.07% positive-review rate** across 114 reviewed orders.
- The second-lowest-rated seller had an average score of **2.69** and a **36.36% positive-review rate** across 198 reviewed orders.
- Several other sellers had average scores close to **3.0**, indicating substantially weaker customer satisfaction than the marketplace-wide average of approximately **4.09**.

These results demonstrate that customer satisfaction varies considerably across sellers.

The findings can be used to identify sellers that may require additional investigation into fulfillment, product quality, delivery performance, or customer-service practices.

The analysis identifies associations in the historical Olist dataset and does not determine the specific cause of poor seller ratings.

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.figure(figsize=(10, 6))

plt.barh(
    bottom_10_sellers["seller_id"],
    bottom_10_sellers["average_review_score"]
)

plt.title("10 Lowest-Rated Sellers (50+ Reviewed Orders)")
plt.xlabel("Average Review Score")
plt.ylabel("Seller ID")

plt.xlim(0, 5)
plt.tight_layout()

plt.show()

## 17.17 Customer Satisfaction Summary

The customer satisfaction analysis examined review scores across delivery performance, delivery-delay severity, product categories, and sellers.

Key findings:

- The overall average review score was **4.09 out of 5**.
- **77.07%** of review records were positive ratings (4–5 stars).
- Early deliveries had an average review score of **4.29**, compared with **2.27** for late deliveries.
- Late deliveries of **8–30 days** were associated with particularly low customer satisfaction, with average review scores below **1.70**.
- Customer satisfaction varied across product categories, with Office Furniture showing a relatively low average score of **3.62** among the categories analyzed.
- Seller-level satisfaction varied substantially. Among sellers with at least 50 reviewed orders, the highest-rated seller had an average score of **4.82**, while the lowest-rated seller had an average score of **2.33**.
- These findings indicate that delivery performance, product category, and seller are all useful dimensions for investigating customer experience.

The analysis identifies associations rather than causal relationships. Product quality, seller operations, delivery performance, customer expectations, and other factors may jointly influence review scores.

All findings describe the historical Olist dataset and should not be interpreted as current industry benchmarks.

# 18. SQL Business Analysis

SQL will be used to answer key business questions from the cleaned e-commerce datasets.

The SQL analysis will focus on:

- Revenue and sales performance
- Monthly sales trends
- Product category performance
- Seller performance
- Customer purchasing behavior
- Delivery performance
- Customer satisfaction
- Geographic performance

The purpose is to demonstrate the ability to transform business questions into SQL queries and extract actionable insights from relational data.

Python was used for data cleaning, exploratory analysis, and advanced customer analysis, while SQL will be used to demonstrate database-oriented analytical skills.

## 18.2 SQL Data Preparation

The main Olist datasets will be loaded into MySQL for SQL-based business analysis.

The core tables will include:

- customers
- orders
- order_items
- order_payments
- order_reviews
- products
- sellers
- geolocation

The tables will retain their original business keys so that relationships can be established between customers, orders, products, sellers, payments, and reviews.

SQL analysis will be performed on the database tables rather than directly modifying the original CSV files.

## 18.3 Creating the SQL Database

A dedicated MySQL database will be created for the e-commerce analytics project.

The database will contain the core Olist tables and will be used for SQL-based business analysis.

The original CSV files will remain unchanged, while MySQL will provide a relational environment for querying the data.

In [ ]:
import os

file_path = r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\olist_customers_dataset.csv"

print(os.path.exists(file_path))

In [ ]:
import pandas as pd

customers_check = pd.read_csv(file_path)

print(customers_check.shape)
print(customers_check.head())

In [ ]:
import os

base_path = r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics"

for root, dirs, files in os.walk(base_path):
    if "olist_customers_dataset.csv" in files:
        print(os.path.join(root, "olist_customers_dataset.csv"))

In [ ]:
import mysql.connector

print("MySQL Connector is working!")

In [ ]:
%pip install mysql-connector-python

In [105]:
import mysql.connector

print("MySQL Connector is working!")

MySQL Connector is working!

In [106]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Rahul@2006",
    database="ecommerce_analytics"
)

print("Connected to MySQL successfully!")

Connected to MySQL successfully!

In [107]:
import pandas as pd

file_path = r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\olist_customers_dataset.csv"

customers = pd.read_csv(file_path)

print(customers.shape)

(99441, 5)

In [108]:
id="x7k2pm"
cursor = conn.cursor()

insert_query = """
INSERT INTO customers
(customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state)
VALUES (%s, %s, %s, %s, %s)
"""

data = [tuple(row) for row in customers.itertuples(index=False, name=None)]

cursor.executemany(insert_query, data)

conn.commit()

print(f"Inserted {cursor.rowcount} rows successfully!")

Inserted 99441 rows successfully!

In [109]:
cursor.execute("SELECT COUNT(*) FROM customers")

count = cursor.fetchone()[0]

print("Customers in MySQL:", count)

Customers in MySQL: 99441

In [110]:
cursor.execute("SELECT * FROM customers LIMIT 5")

for row in cursor.fetchall():
    print(row)

('06b8999e2fba1a1fbc88172c00ba8bc7', '861eff4711a542e4b93843c6dd7febb0', 14409, 'franca', 'SP')
('18955e83d337fd6b2def6b18a428ac77', '290c77bc529b7ac935b93aa66c333dc3', 9790, 'sao bernardo do campo', 'SP')
('4e7b3e00288586ebd08712fdd0374a03', '060e732b5b29e8181a18229c7b0b2b5e', 1151, 'sao paulo', 'SP')
('b2b6027bc5c5109e529d4dc6358b12c3', '259dac757896d24d7702b9acbbff3f3c', 8775, 'mogi das cruzes', 'SP')
('4f2d8ab171c80ec8364f7c12e35b23ad', '345ecd01c38d18a9036ed96c73b8d066', 13056, 'campinas', 'SP')

In [111]:
orders = pd.read_csv(
    r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\olist_orders_dataset.csv"
)

print(orders.shape)

(99441, 8)

In [112]:
print(orders.columns.tolist())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

In [113]:
cursor = conn.cursor()

insert_query = """
INSERT INTO orders
(
    order_id,
    customer_id,
    order_status,
    order_purchase_timestamp,
    order_approved_at,
    order_delivered_carrier_date,
    order_delivered_customer_date,
    order_estimated_delivery_date
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
"""

data = [
    tuple(None if pd.isna(value) else value for value in row)
    for row in orders.itertuples(index=False, name=None)
]

cursor.executemany(insert_query, data)

conn.commit()

print(f"Inserted {cursor.rowcount} orders successfully!")

Inserted 99441 orders successfully!

In [114]:
order_items = pd.read_csv(
    r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\olist_order_items_dataset.csv"
)

print(order_items.shape)

(112650, 7)

In [115]:
print(order_items.columns.tolist())

['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

In [116]:
cursor = conn.cursor()

insert_query = """
INSERT INTO order_items
(
    order_id,
    order_item_id,
    product_id,
    seller_id,
    shipping_limit_date,
    price,
    freight_value
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

data = [
    tuple(None if pd.isna(value) else value for value in row)
    for row in order_items.itertuples(index=False, name=None)
]

cursor.executemany(insert_query, data)

conn.commit()

print(f"Inserted {cursor.rowcount} order items successfully!")

Inserted 112650 order items successfully!

In [117]:
products = pd.read_csv(
    r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\olist_products_dataset.csv"
)

print(products.shape)
print(products.columns.tolist())

(32951, 9)
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

In [118]:
cursor = conn.cursor()

insert_query = """
INSERT INTO products
(
    product_id,
    product_category_name,
    product_name_lenght,
    product_description_lenght,
    product_photos_qty,
    product_weight_g,
    product_length_cm,
    product_height_cm,
    product_width_cm
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

data = [
    tuple(None if pd.isna(value) else value for value in row)
    for row in products.itertuples(index=False, name=None)
]

cursor.executemany(insert_query, data)

conn.commit()

print(f"Inserted {cursor.rowcount} products successfully!")

Inserted 32951 products successfully!

In [119]:
sellers = pd.read_csv(
    r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\olist_sellers_dataset.csv"
)

print(sellers.shape)
print(sellers.columns.tolist())

(3095, 4)
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [120]:
cursor = conn.cursor()

insert_query = """
INSERT INTO sellers
(
    seller_id,
    seller_zip_code_prefix,
    seller_city,
    seller_state
)
VALUES (%s, %s, %s, %s)
"""

data = [
    tuple(None if pd.isna(value) else value
          for value in row)
    for row in sellers.itertuples(index=False, name=None)
]

cursor.executemany(insert_query, data)
conn.commit()

print(f"Inserted {cursor.rowcount} sellers successfully!")

Inserted 3095 sellers successfully!

In [121]:
order_reviews = pd.read_csv(
    r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\olist_order_reviews_dataset.csv"
)

print(order_reviews.shape)
print(order_reviews.columns.tolist())

(99224, 7)
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

In [122]:
cursor = conn.cursor()

insert_query = """
INSERT INTO order_reviews
(
    review_id,
    order_id,
    review_score,
    review_comment_title,
    review_comment_message,
    review_creation_date,
    review_answer_timestamp
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

data = [
    tuple(None if pd.isna(value) else value
          for value in row)
    for row in order_reviews.itertuples(index=False, name=None)
]

cursor.executemany(insert_query, data)
conn.commit()

print(f"Inserted {cursor.rowcount} reviews successfully!")

Inserted 99224 reviews successfully!

In [123]:
order_payments = pd.read_csv(
    r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\olist_order_payments_dataset.csv"
)

print(order_payments.shape)
print(order_payments.columns.tolist())

(103886, 5)
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

In [124]:
cursor = conn.cursor()

insert_query = """
INSERT INTO order_payments
(
    order_id,
    payment_sequential,
    payment_type,
    payment_installments,
    payment_value
)
VALUES (%s, %s, %s, %s, %s)
"""

data = [
    tuple(None if pd.isna(value) else value
          for value in row)
    for row in order_payments.itertuples(index=False, name=None)
]

cursor.executemany(insert_query, data)
conn.commit()

print(f"Inserted {cursor.rowcount} payment records successfully!")

Inserted 103886 payment records successfully!

In [125]:
category_translation = pd.read_csv(
    r"C:\Users\ASUS\E-Commerce-Marketplace-Analytics\Data\Raw\product_category_name_translation.csv"
)

print(category_translation.shape)
print(category_translation.columns.tolist())

(71, 2)
['product_category_name', 'product_category_name_english']

In [126]:
cursor = conn.cursor()

insert_query = """
INSERT INTO category_translation
(
    product_category_name,
    product_category_name_english
)
VALUES (%s, %s)
"""

data = [
    tuple(None if pd.isna(value) else value
          for value in row)
    for row in category_translation.itertuples(index=False, name=None)
]

cursor.executemany(insert_query, data)
conn.commit()

print(f"Inserted {cursor.rowcount} category translations successfully!")

Inserted 71 category translations successfully!